// Code generated by protoc-gen-go. DO NOT EDIT.
// source: v1/admin.proto

package keytransparency_go_proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"
import google_protobuf1 "github.com/golang/protobuf/ptypes/any"
import google_protobuf4 "github.com/golang/protobuf/ptypes/empty"
import google_protobuf2 "github.com/golang/protobuf/ptypes/duration"
import trillian "github.com/google/trillian"
import keyspb "github.com/google/trillian/crypto/keyspb"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Domain contains information on a single domain
type Domain struct {
	// DomainId can be any URL safe string.
	DomainId string `protobuf:"bytes,1,opt,name=domain_id,json=domainId" json:"domain_id,omitempty"`
	// Log contains the Log-Tree's info.
	Log *trillian.Tree `protobuf:"bytes,2,opt,name=log" json:"log,omitempty"`
	// Map contains the Map-Tree's info.
	Map *trillian.Tree `protobuf:"bytes,3,opt,name=map" json:"map,omitempty"`
	// Vrf contains the VRF public key.
	Vrf *keyspb.PublicKey `protobuf:"bytes,4,opt,name=vrf" json:"vrf,omitempty"`
	// min_interval is the minimum time between epochs.
	MinInterval *google_protobuf2.Duration `protobuf:"bytes,5,opt,name=min_interval,json=minInterval" json:"min_interval,omitempty"`
	// max_interval is the maximum time between epochs.
	MaxInterval *google_protobuf2.Duration `protobuf:"bytes,6,opt,name=max_interval,json=maxInterval" json:"max_interval,omitempty"`
	// Deleted indicates whether the domain has been marked as deleted.
	// By its presence in a response, this domain has not been garbage collected.
	Deleted bool `protobuf:"varint,7,opt,name=deleted" json:"deleted,omitempty"`
}

func (m *Domain) Reset()                    { *m = Domain{} }
func (m *Domain) String() string            { return proto.CompactTextString(m) }
func (*Domain) ProtoMessage()               {}
func (*Domain) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *Domain) GetDomainId() string {
	if m != nil {
		return m.DomainId
	}
	return ""
}

func (m *Domain) GetLog() *trillian.Tree {
	if m != nil {
		return m.Log
	}
	return nil
}

func (m *Domain) GetMap() *trillian.Tree {
	if m != nil {
		return m.Map
	}
	return nil
}

func (m *Domain) GetVrf() *keyspb.PublicKey {
	if m != nil {
		return m.Vrf
	}
	return nil
}

func (m *Domain) GetMinInterval() *google_protobuf2.Duration {
	if m != nil {
		return m.MinInterval
	}
	return nil
}

func (m *Domain) GetMaxInterval() *google_protobuf2.Duration {
	if m != nil {
		return m.MaxInterval
	}
	return nil
}

func (m *Domain) GetDeleted() bool {
	if m != nil {
		return m.Deleted
	}
	return false
}

// ListDomains request.
// No pagination options are provided.
type ListDomainsRequest struct {
	// showDeleted requests domains that have been marked for deletion
	// but have not been garbage collected.
	ShowDeleted bool `protobuf:"varint,1,opt,name=show_deleted,json=showDeleted" json:"show_deleted,omitempty"`
}

func (m *ListDomainsRequest) Reset()                    { *m = ListDomainsRequest{} }
func (m *ListDomainsRequest) String() string            { return proto.CompactTextString(m) }
func (*ListDomainsRequest) ProtoMessage()               {}
func (*ListDomainsRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *ListDomainsRequest) GetShowDeleted() bool {
	if m != nil {
		return m.ShowDeleted
	}
	return false
}

// ListDomains response contains domains.
type ListDomainsResponse struct {
	Domains []*Domain `protobuf:"bytes,1,rep,name=domains" json:"domains,omitempty"`
}

func (m *ListDomainsResponse) Reset()                    { *m = ListDomainsResponse{} }
func (m *ListDomainsResponse) String() string            { return proto.CompactTextString(m) }
func (*ListDomainsResponse) ProtoMessage()               {}
func (*ListDomainsResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *ListDomainsResponse) GetDomains() []*Domain {
	if m != nil {
		return m.Domains
	}
	return nil
}

// GetDomainRequest specifies the domain to retrieve information for.
type GetDomainRequest struct {
	DomainId string `protobuf:"bytes,1,opt,name=domain_id,json=domainId" json:"domain_id,omitempty"`
	// showDeleted requests domains that have been marked for deletion
	// but have not been garbage collected.
	ShowDeleted bool `protobuf:"varint,2,opt,name=show_deleted,json=showDeleted" json:"show_deleted,omitempty"`
}

func (m *GetDomainRequest) Reset()                    { *m = GetDomainRequest{} }
func (m *GetDomainRequest) String() string            { return proto.CompactTextString(m) }
func (*GetDomainRequest) ProtoMessage()               {}
func (*GetDomainRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *GetDomainRequest) GetDomainId() string {
	if m != nil {
		return m.DomainId
	}
	return ""
}

func (m *GetDomainRequest) GetShowDeleted() bool {
	if m != nil {
		return m.ShowDeleted
	}
	return false
}

// CreateDomainRequest creates a new domain
type CreateDomainRequest struct {
	DomainId    string                     `protobuf:"bytes,1,opt,name=domain_id,json=domainId" json:"domain_id,omitempty"`
	MinInterval *google_protobuf2.Duration `protobuf:"bytes,2,opt,name=min_interval,json=minInterval" json:"min_interval,omitempty"`
	MaxInterval *google_protobuf2.Duration `protobuf:"bytes,3,opt,name=max_interval,json=maxInterval" json:"max_interval,omitempty"`
	// The private_key fields allows callers to set the private key.
	VrfPrivateKey *google_protobuf1.Any `protobuf:"bytes,4,opt,name=vrf_private_key,json=vrfPrivateKey" json:"vrf_private_key,omitempty"`
	LogPrivateKey *google_protobuf1.Any `protobuf:"bytes,5,opt,name=log_private_key,json=logPrivateKey" json:"log_private_key,omitempty"`
	MapPrivateKey *google_protobuf1.Any `protobuf:"bytes,6,opt,name=map_private_key,json=mapPrivateKey" json:"map_private_key,omitempty"`
}

func (m *CreateDomainRequest) Reset()                    { *m = CreateDomainRequest{} }
func (m *CreateDomainRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateDomainRequest) ProtoMessage()               {}
func (*CreateDomainRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

func (m *CreateDomainRequest) GetDomainId() string {
	if m != nil {
		return m.DomainId
	}
	return ""
}

func (m *CreateDomainRequest) GetMinInterval() *google_protobuf2.Duration {
	if m != nil {
		return m.MinInterval
	}
	return nil
}

func (m *CreateDomainRequest) GetMaxInterval() *google_protobuf2.Duration {
	if m != nil {
		return m.MaxInterval
	}
	return nil
}

func (m *CreateDomainRequest) GetVrfPrivateKey() *google_protobuf1.Any {
	if m != nil {
		return m.VrfPrivateKey
	}
	return nil
}

func (m *CreateDomainRequest) GetLogPrivateKey() *google_protobuf1.Any {
	if m != nil {
		return m.LogPrivateKey
	}
	return nil
}

func (m *CreateDomainRequest) GetMapPrivateKey() *google_protobuf1.Any {
	if m != nil {
		return m.MapPrivateKey
	}
	return nil
}

// DeleteDomainRequest deletes a domain
type DeleteDomainRequest struct {
	DomainId string `protobuf:"bytes,1,opt,name=domain_id,json=domainId" json:"domain_id,omitempty"`
}

func (m *DeleteDomainRequest) Reset()                    { *m = DeleteDomainRequest{} }
func (m *DeleteDomainRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteDomainRequest) ProtoMessage()               {}
func (*DeleteDomainRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{5} }

func (m *DeleteDomainRequest) GetDomainId() string {
	if m != nil {
		return m.DomainId
	}
	return ""
}

// UndeleteDomainRequest deletes a domain
type UndeleteDomainRequest struct {
	DomainId string `protobuf:"bytes,1,opt,name=domain_id,json=domainId" json:"domain_id,omitempty"`
}

func (m *UndeleteDomainRequest) Reset()                    { *m = UndeleteDomainRequest{} }
func (m *UndeleteDomainRequest) String() string            { return proto.CompactTextString(m) }
func (*UndeleteDomainRequest) ProtoMessage()               {}
func (*UndeleteDomainRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{6} }

func (m *UndeleteDomainRequest) GetDomainId() string {
	if m != nil {
		return m.DomainId
	}
	return ""
}

func init() {
	proto.RegisterType((*Domain)(nil), "google.keytransparency.v1.Domain")
	proto.RegisterType((*ListDomainsRequest)(nil), "google.keytransparency.v1.ListDomainsRequest")
	proto.RegisterType((*ListDomainsResponse)(nil), "google.keytransparency.v1.ListDomainsResponse")
	proto.RegisterType((*GetDomainRequest)(nil), "google.keytransparency.v1.GetDomainRequest")
	proto.RegisterType((*CreateDomainRequest)(nil), "google.keytransparency.v1.CreateDomainRequest")
	proto.RegisterType((*DeleteDomainRequest)(nil), "google.keytransparency.v1.DeleteDomainRequest")
	proto.RegisterType((*UndeleteDomainRequest)(nil), "google.keytransparency.v1.UndeleteDomainRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for KeyTransparencyAdmin service

type KeyTransparencyAdminClient interface {
	// ListDomains returns a list of all domains this Key Transparency server
	// operates on.
	ListDomains(ctx context.Context, in *ListDomainsRequest, opts ...grpc.CallOption) (*ListDomainsResponse, error)
	// GetDomain returns the confiuration information for a given domain.
	GetDomain(ctx context.Context, in *GetDomainRequest, opts ...grpc.CallOption) (*Domain, error)
	// CreateDomain creates a new Trillian log/map pair.  A unique domainId must
	// be provided.  To create a new domain with the same name as a previously
	// deleted domain, a user must wait X days until the domain is garbage
	// collected.
	CreateDomain(ctx context.Context, in *CreateDomainRequest, opts ...grpc.CallOption) (*Domain, error)
	// DeleteDomain marks a domain as deleted.  Domains will be garbage collected
	// after X days.
	DeleteDomain(ctx context.Context, in *DeleteDomainRequest, opts ...grpc.CallOption) (*google_protobuf4.Empty, error)
	// UndeleteDomain marks a previously deleted domain as active if it has not
	// already been garbage collected.
	UndeleteDomain(ctx context.Context, in *UndeleteDomainRequest, opts ...grpc.CallOption) (*google_protobuf4.Empty, error)
}

type keyTransparencyAdminClient struct {
	cc *grpc.ClientConn
}

func NewKeyTransparencyAdminClient(cc *grpc.ClientConn) KeyTransparencyAdminClient {
	return &keyTransparencyAdminClient{cc}
}

func (c *keyTransparencyAdminClient) ListDomains(ctx context.Context, in *ListDomainsRequest, opts ...grpc.CallOption) (*ListDomainsResponse, error) {
	out := new(ListDomainsResponse)
	err := grpc.Invoke(ctx, "/google.keytransparency.v1.KeyTransparencyAdmin/ListDomains", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyTransparencyAdminClient) GetDomain(ctx context.Context, in *GetDomainRequest, opts ...grpc.CallOption) (*Domain, error) {
	out := new(Domain)
	err := grpc.Invoke(ctx, "/google.keytransparency.v1.KeyTransparencyAdmin/GetDomain", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyTransparencyAdminClient) CreateDomain(ctx context.Context, in *CreateDomainRequest, opts ...grpc.CallOption) (*Domain, error) {
	out := new(Domain)
	err := grpc.Invoke(ctx, "/google.keytransparency.v1.KeyTransparencyAdmin/CreateDomain", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyTransparencyAdminClient) DeleteDomain(ctx context.Context, in *DeleteDomainRequest, opts ...grpc.CallOption) (*google_protobuf4.Empty, error) {
	out := new(google_protobuf4.Empty)
	err := grpc.Invoke(ctx, "/google.keytransparency.v1.KeyTransparencyAdmin/DeleteDomain", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyTransparencyAdminClient) UndeleteDomain(ctx context.Context, in *UndeleteDomainRequest, opts ...grpc.CallOption) (*google_protobuf4.Empty, error) {
	out := new(google_protobuf4.Empty)
	err := grpc.Invoke(ctx, "/google.keytransparency.v1.KeyTransparencyAdmin/UndeleteDomain", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for KeyTransparencyAdmin service

type KeyTransparencyAdminServer interface {
	// ListDomains returns a list of all domains this Key Transparency server
	// operates on.
	ListDomains(context.Context, *ListDomainsRequest) (*ListDomainsResponse, error)
	// GetDomain returns the confiuration information for a given domain.
	GetDomain(context.Context, *GetDomainRequest) (*Domain, error)
	// CreateDomain creates a new Trillian log/map pair.  A unique domainId must
	// be provided.  To create a new domain with the same name as a previously
	// deleted domain, a user must wait X days until the domain is garbage
	// collected.
	CreateDomain(context.Context, *CreateDomainRequest) (*Domain, error)
	// DeleteDomain marks a domain as deleted.  Domains will be garbage collected
	// after X days.
	DeleteDomain(context.Context, *DeleteDomainRequest) (*google_protobuf4.Empty, error)
	// UndeleteDomain marks a previously deleted domain as active if it has not
	// already been garbage collected.
	UndeleteDomain(context.Context, *UndeleteDomainRequest) (*google_protobuf4.Empty, error)
}

func RegisterKeyTransparencyAdminServer(s *grpc.Server, srv KeyTransparencyAdminServer) {
	s.RegisterService(&_KeyTransparencyAdmin_serviceDesc, srv)
}

func _KeyTransparencyAdmin_ListDomains_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDomainsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyTransparencyAdminServer).ListDomains(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/google.keytransparency.v1.KeyTransparencyAdmin/ListDomains",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyTransparencyAdminServer).ListDomains(ctx, req.(*ListDomainsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyTransparencyAdmin_GetDomain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDomainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyTransparencyAdminServer).GetDomain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/google.keytransparency.v1.KeyTransparencyAdmin/GetDomain",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyTransparencyAdminServer).GetDomain(ctx, req.(*GetDomainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyTransparencyAdmin_CreateDomain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDomainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyTransparencyAdminServer).CreateDomain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/google.keytransparency.v1.KeyTransparencyAdmin/CreateDomain",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyTransparencyAdminServer).CreateDomain(ctx, req.(*CreateDomainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyTransparencyAdmin_DeleteDomain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDomainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyTransparencyAdminServer).DeleteDomain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/google.keytransparency.v1.KeyTransparencyAdmin/DeleteDomain",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyTransparencyAdminServer).DeleteDomain(ctx, req.(*DeleteDomainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyTransparencyAdmin_UndeleteDomain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UndeleteDomainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyTransparencyAdminServer).UndeleteDomain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/google.keytransparency.v1.KeyTransparencyAdmin/UndeleteDomain",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyTransparencyAdminServer).UndeleteDomain(ctx, req.(*UndeleteDomainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _KeyTransparencyAdmin_serviceDesc = grpc.ServiceDesc{
	ServiceName: "google.keytransparency.v1.KeyTransparencyAdmin",
	HandlerType: (*KeyTransparencyAdminServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListDomains",
			Handler:    _KeyTransparencyAdmin_ListDomains_Handler,
		},
		{
			MethodName: "GetDomain",
			Handler:    _KeyTransparencyAdmin_GetDomain_Handler,
		},
		{
			MethodName: "CreateDomain",
			Handler:    _KeyTransparencyAdmin_CreateDomain_Handler,
		},
		{
			MethodName: "DeleteDomain",
			Handler:    _KeyTransparencyAdmin_DeleteDomain_Handler,
		},
		{
			MethodName: "UndeleteDomain",
			Handler:    _KeyTransparencyAdmin_UndeleteDomain_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v1/admin.proto",
}

func init() { proto.RegisterFile("v1/admin.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 676 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x95, 0xcf, 0x6e, 0xd3, 0x30,
	0x1c, 0xc7, 0x95, 0x96, 0x75, 0x9b, 0xdb, 0x95, 0xe1, 0x8e, 0x91, 0x75, 0x08, 0xba, 0x70, 0xa9,
	0x86, 0x48, 0x68, 0x41, 0x42, 0x1a, 0xbb, 0x8c, 0x6d, 0x42, 0xd3, 0x38, 0x4c, 0xd1, 0xb8, 0x70,
	0xa9, 0xdc, 0xc6, 0xed, 0xa2, 0x25, 0xb6, 0x71, 0xdc, 0x6c, 0x11, 0x70, 0x00, 0xf1, 0x06, 0x7b,
	0x05, 0xde, 0x88, 0x57, 0xe0, 0xc0, 0x63, 0xa0, 0xc4, 0x4e, 0xd7, 0xa6, 0x6d, 0xb6, 0x89, 0x53,
	0xea, 0xfc, 0x7e, 0x9f, 0xdf, 0xdf, 0x6f, 0x6a, 0x50, 0x0d, 0x5b, 0x16, 0x72, 0x7c, 0x97, 0x98,
	0x8c, 0x53, 0x41, 0xe1, 0xc6, 0x80, 0xd2, 0x81, 0x87, 0xcd, 0x73, 0x1c, 0x09, 0x8e, 0x48, 0xc0,
	0x10, 0xc7, 0xa4, 0x17, 0x99, 0x61, 0xab, 0xfe, 0x58, 0x9a, 0x2c, 0xc4, 0x5c, 0x0b, 0x11, 0x42,
	0x05, 0x12, 0x2e, 0x25, 0x81, 0x04, 0xeb, 0x0a, 0xb4, 0x92, 0x53, 0x77, 0xd8, 0xb7, 0x10, 0x89,
	0x94, 0x69, 0x33, 0x6b, 0xc2, 0x3e, 0x13, 0xa9, 0xf1, 0x49, 0xd6, 0xe8, 0x0c, 0x79, 0x12, 0x58,
	0xd9, 0xab, 0x82, 0xbb, 0x9e, 0xe7, 0xa2, 0xf4, 0x5c, 0xef, 0xf1, 0x88, 0x09, 0x6a, 0x9d, 0xe3,
	0x28, 0x60, 0x5d, 0xf5, 0x90, 0x36, 0xe3, 0x57, 0x01, 0x94, 0x0e, 0xa8, 0x8f, 0x5c, 0x02, 0x37,
	0xc1, 0xb2, 0x93, 0xfc, 0xea, 0xb8, 0x8e, 0xae, 0x35, 0xb4, 0xe6, 0xb2, 0xbd, 0x24, 0x5f, 0x1c,
	0x39, 0xb0, 0x01, 0x8a, 0x1e, 0x1d, 0xe8, 0x85, 0x86, 0xd6, 0x2c, 0xb7, 0xab, 0xe6, 0x28, 0xc3,
	0x29, 0xc7, 0xd8, 0x8e, 0x4d, 0xb1, 0x87, 0x8f, 0x98, 0x5e, 0x9c, 0xed, 0xe1, 0x23, 0x06, 0x9f,
	0x81, 0x62, 0xc8, 0xfb, 0xfa, 0xbd, 0xc4, 0xe3, 0x81, 0xa9, 0xea, 0x38, 0x19, 0x76, 0x3d, 0xb7,
	0x77, 0x8c, 0x23, 0x3b, 0xb6, 0xc2, 0x5d, 0x50, 0xf1, 0xe3, 0x12, 0x88, 0xc0, 0x3c, 0x44, 0x9e,
	0xbe, 0x90, 0x78, 0x6f, 0x98, 0x6a, 0xc8, 0x69, 0xcf, 0xe6, 0x81, 0xea, 0xd9, 0x2e, 0xfb, 0x2e,
	0x39, 0x52, 0xde, 0x09, 0x8d, 0x2e, 0xaf, 0xe9, 0xd2, 0xcd, 0x34, 0xba, 0x1c, 0xd1, 0x3a, 0x58,
	0x74, 0xb0, 0x87, 0x05, 0x76, 0xf4, 0xc5, 0x86, 0xd6, 0x5c, 0xb2, 0xd3, 0xa3, 0xf1, 0x06, 0xc0,
	0x0f, 0x6e, 0x20, 0xe4, 0xa4, 0x02, 0x1b, 0x7f, 0x1e, 0xe2, 0x40, 0xc0, 0x2d, 0x50, 0x09, 0xce,
	0xe8, 0x45, 0x27, 0x85, 0xb4, 0x04, 0x2a, 0xc7, 0xef, 0x0e, 0x14, 0x68, 0x83, 0xda, 0x04, 0x18,
	0x30, 0x4a, 0x02, 0x0c, 0xdf, 0x82, 0x45, 0x39, 0xda, 0x40, 0xd7, 0x1a, 0xc5, 0x66, 0xb9, 0xbd,
	0x65, 0xce, 0x55, 0x91, 0x29, 0x61, 0x3b, 0x25, 0x0c, 0x1b, 0xac, 0xbe, 0xc7, 0x2a, 0x64, 0x5a,
	0x4a, 0xee, 0xf2, 0xb2, 0x75, 0x16, 0xa6, 0xeb, 0xfc, 0x5b, 0x00, 0xb5, 0x7d, 0x8e, 0x91, 0xc0,
	0x77, 0x88, 0x9b, 0xdd, 0x55, 0xe1, 0xbf, 0x76, 0x55, 0xbc, 0xd3, 0xae, 0x76, 0xc1, 0xfd, 0x90,
	0xf7, 0x3b, 0x8c, 0xbb, 0x21, 0x12, 0xb8, 0x73, 0x8e, 0x23, 0x25, 0xac, 0xb5, 0xa9, 0x00, 0x7b,
	0x24, 0xb2, 0x57, 0x42, 0xde, 0x3f, 0x91, 0xbe, 0xc7, 0x38, 0x8a, 0x69, 0x8f, 0x0e, 0x26, 0xe8,
	0x85, 0x3c, 0xda, 0xa3, 0x83, 0x49, 0xda, 0x47, 0x6c, 0x82, 0x2e, 0xe5, 0xd1, 0x3e, 0x62, 0xd7,
	0xb4, 0xd1, 0x06, 0x35, 0x39, 0xf5, 0xdb, 0x4f, 0xda, 0x78, 0x0d, 0x1e, 0x7e, 0x24, 0xce, 0x1d,
	0xa9, 0xf6, 0xd5, 0x02, 0x58, 0x3b, 0xc6, 0xd1, 0xe9, 0x98, 0x9e, 0xf6, 0xe2, 0x3f, 0x2e, 0xf8,
	0x5d, 0x03, 0xe5, 0x31, 0x59, 0xc2, 0x17, 0x39, 0xea, 0x9b, 0xd6, 0x7d, 0xdd, 0xbc, 0xad, 0xbb,
	0x54, 0xbb, 0x51, 0xfb, 0xf1, 0xfb, 0xcf, 0x55, 0x61, 0x05, 0x96, 0xad, 0xb0, 0x65, 0x29, 0x15,
	0xc3, 0xaf, 0x60, 0x79, 0xa4, 0x62, 0xf8, 0x3c, 0x27, 0x62, 0x56, 0xeb, 0xf5, 0x9b, 0xbf, 0x15,
	0xe3, 0x69, 0x92, 0x71, 0x03, 0x3e, 0x1a, 0xcb, 0x68, 0x7d, 0x19, 0x4d, 0xea, 0x1b, 0x8c, 0x40,
	0x65, 0x5c, 0xee, 0x30, 0xaf, 0xa5, 0x19, 0xdf, 0xc5, 0x6d, 0x6a, 0x58, 0x4f, 0x6a, 0x58, 0x35,
	0xc6, 0xbb, 0xde, 0xd1, 0xb6, 0xe1, 0x05, 0xa8, 0x8c, 0xef, 0x3f, 0x37, 0xf5, 0x0c, 0xa1, 0xd4,
	0xd7, 0xa7, 0x44, 0x76, 0x18, 0x5f, 0x0e, 0x69, 0xcf, 0xdb, 0x73, 0x7b, 0xfe, 0xa9, 0x81, 0xea,
	0xa4, 0x8a, 0xe0, 0xcb, 0x9c, 0xdc, 0x33, 0x05, 0x37, 0x37, 0x7b, 0x33, 0xc9, 0x6e, 0x6c, 0x37,
	0xe6, 0x64, 0xdf, 0x19, 0xaa, 0x70, 0xef, 0x0e, 0x3f, 0xed, 0x0f, 0x5c, 0x71, 0x36, 0xec, 0x9a,
	0x3d, 0xea, 0x5b, 0xea, 0x2e, 0xcb, 0xe4, 0xb7, 0x7a, 0x94, 0xcb, 0x6b, 0x33, 0x6c, 0x65, 0x6d,
	0x1d, 0x99, 0xb9, 0x94, 0x3c, 0x5e, 0xfd, 0x0b, 0x00, 0x00, 0xff, 0xff, 0xa6, 0x26, 0x56, 0x34,
	0x8f, 0x07, 0x00, 0x00,
}
