run:
  timeout: 5m

linters-settings:
  govet:
    check-shadowing: false
  golint:
    min-confidence: 0.2
  gocyclo:
    min-complexity: 18
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 3
  misspell:
    locale: US
  depguard:
    list-type: blacklist
    packages:
      - golang.org/x/net/context
      - github.com/gogo/protobuf/proto
      - github.com/google/martian/log

linters:
  enable-all: true
  disable:
    - maligned
    - scopelint
    - gochecknoinits
    - gochecknoglobals
    - lll
    - interfacer

issues:
  exclude:
    - .(.*Write|.*Serve).
