#!/bin/sh
# Preconditions:

# protoc compiler > 2.6.1 from https://github.com/google/protobuf
apt-get install build-essential
git clone git@github.com:google/protobuf.git $GOPATH/src/github.com/google/protobuf
cd $GOPATH/src/github.com/google/protobuf
./autogen.sh
./configure
make
make check
make install
ldconfig

# go code gen plugin at https://github.com/golang/protobuf
go get -u github.com/golang/protobuf/proto
go get -u github.com/golang/protobuf/protoc-gen-go
go get -u golang.org/x/net/context

# Non go packages

# Proto3 types.  Needs to go in $(GOPATH)/src.
git clone git@github.com:google/googleapis.git $GOPATH/src/github.com/google/googleapis
ln -s $GOPATH/src/github.com/google/googleapis/google $GOPATH/src/google

#Shell PATH must include $GOPATH/bin
