#!/bin/sh

# Copyright 2016 Google Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Preconditions:

# protoc compiler > 2.6.1 from https://github.com/google/protobuf
version=`protoc --version | awk '{printf("%d.%d", $2, $3);};'`
if [[ "$version" < "3.0" ]]; then
	echo "protoc --version $version < 3.0."
	echo "Installing protoc"
	apt-get install build-essential
	apt-get install autoconf automake libtool
	git clone git@github.com:google/protobuf.git $GOPATH/src/github.com/google/protobuf
	cd $GOPATH/src/github.com/google/protobuf
	./autogen.sh
	./configure
	make
	make check
	make install
	ldconfig
fi

# go code gen plugin at https://github.com/golang/protobuf
go get -u github.com/golang/protobuf/proto
go get -u github.com/golang/protobuf/protoc-gen-go
go get -u github.com/gorilla/mux
go get -u golang.org/x/net/context
go get -u golang.org/x/crypto/openpgp
go get -u google.golang.org/grpc
go get -u github.com/mattn/go-sqlite3

#Shell PATH must include $GOPATH/bin
