// Code generated by protoc-gen-go. DO NOT EDIT.
// source: monitor_v1_proto.proto

/*
Package monitor_v1_proto is a generated protocol buffer package.

Key Transparency Monitor Service


It is generated from these files:
	monitor_v1_proto.proto

It has these top-level messages:
	GetMonitoringRequest
	GetMonitoringResponse
*/
package monitor_v1_proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import keytransparency_v1_proto "github.com/google/keytransparency/core/proto/keytransparency_v1_proto"
import trillian "github.com/google/trillian"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// GetMonitoringRequest contains the input parameters of the GetMonitoring APIs.
type GetMonitoringRequest struct {
	// epoch specifies the for which the monitoring results will
	// be returned (epochs start at 1).
	Epoch int64 `protobuf:"varint,1,opt,name=epoch" json:"epoch,omitempty"`
	// kt_URL is the URL of the keytransparency server for which the monitoring
	// result will be returned.
	Kt_URL string `protobuf:"bytes,2,opt,name=kt_URL,json=ktURL" json:"kt_URL,omitempty"`
}

func (m *GetMonitoringRequest) Reset()                    { *m = GetMonitoringRequest{} }
func (m *GetMonitoringRequest) String() string            { return proto.CompactTextString(m) }
func (*GetMonitoringRequest) ProtoMessage()               {}
func (*GetMonitoringRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *GetMonitoringRequest) GetEpoch() int64 {
	if m != nil {
		return m.Epoch
	}
	return 0
}

func (m *GetMonitoringRequest) GetKt_URL() string {
	if m != nil {
		return m.Kt_URL
	}
	return ""
}

type GetMonitoringResponse struct {
	// smr contains the map root for the sparse Merkle Tree signed with the
	// monitor's key on success. If the checks were not successful the
	// smr will be empty. The epochs are encoded into the smr map_revision.
	Smr *trillian.SignedMapRoot `protobuf:"bytes,1,opt,name=smr" json:"smr,omitempty"`
	// seen_timestamp_nanos contains the time in nanoseconds where this particular
	// signed map root was retrieved and processed. The actual timestamp of the
	// smr returned by the server is contained in above smr field.
	SeenTimestampNanos int64 `protobuf:"varint,2,opt,name=seen_timestamp_nanos,json=seenTimestampNanos" json:"seen_timestamp_nanos,omitempty"`
	// errors contains a list of error string representing the verification checks
	// that failed while monitoring the key-transparency server.
	Errors []string `protobuf:"bytes,3,rep,name=errors" json:"errors,omitempty"`
	// error_data contains the original response from the mutations API if and
	// only if at least one verification step failed. It can be used to re-run the
	// verification steps.
	ErrorData *keytransparency_v1_proto.GetMutationsResponse `protobuf:"bytes,4,opt,name=error_data,json=errorData" json:"error_data,omitempty"`
}

func (m *GetMonitoringResponse) Reset()                    { *m = GetMonitoringResponse{} }
func (m *GetMonitoringResponse) String() string            { return proto.CompactTextString(m) }
func (*GetMonitoringResponse) ProtoMessage()               {}
func (*GetMonitoringResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GetMonitoringResponse) GetSmr() *trillian.SignedMapRoot {
	if m != nil {
		return m.Smr
	}
	return nil
}

func (m *GetMonitoringResponse) GetSeenTimestampNanos() int64 {
	if m != nil {
		return m.SeenTimestampNanos
	}
	return 0
}

func (m *GetMonitoringResponse) GetErrors() []string {
	if m != nil {
		return m.Errors
	}
	return nil
}

func (m *GetMonitoringResponse) GetErrorData() *keytransparency_v1_proto.GetMutationsResponse {
	if m != nil {
		return m.ErrorData
	}
	return nil
}

func init() {
	proto.RegisterType((*GetMonitoringRequest)(nil), "monitor.v1.proto.GetMonitoringRequest")
	proto.RegisterType((*GetMonitoringResponse)(nil), "monitor.v1.proto.GetMonitoringResponse")
}

func init() { proto.RegisterFile("monitor_v1_proto.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 299 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0x41, 0x6b, 0x3a, 0x31,
	0x10, 0xc5, 0xd9, 0xff, 0xfe, 0x15, 0x4c, 0xa1, 0x94, 0xa0, 0x76, 0xe9, 0x49, 0x3c, 0xd9, 0x4b,
	0xb6, 0xb6, 0x1f, 0xa1, 0x85, 0x5e, 0xb4, 0x87, 0xb4, 0x9e, 0x43, 0x5c, 0x87, 0x35, 0xe8, 0x66,
	0xd2, 0x64, 0x14, 0xfc, 0xac, 0xfd, 0x32, 0x65, 0xb3, 0xeb, 0x1e, 0x16, 0x7a, 0x09, 0x99, 0xf9,
	0x3d, 0xde, 0x7b, 0x0c, 0x9b, 0x56, 0x68, 0x0d, 0xa1, 0x57, 0xe7, 0xa5, 0x72, 0x1e, 0x09, 0x45,
	0x7c, 0xf9, 0x5d, 0xbb, 0x17, 0xe7, 0x65, 0xb3, 0x79, 0xd8, 0x95, 0x86, 0xf6, 0xa7, 0xad, 0x28,
	0xb0, 0xca, 0x4b, 0xc4, 0xf2, 0x08, 0xf9, 0x01, 0x2e, 0xe4, 0xb5, 0x0d, 0x4e, 0x7b, 0xb0, 0xc5,
	0x25, 0x2f, 0xd0, 0x43, 0x1e, 0xd5, 0x7d, 0xd4, 0xd9, 0xff, 0x09, 0xda, 0x94, 0x5b, 0xf2, 0xe6,
	0x78, 0x34, 0xda, 0x36, 0xf3, 0xfc, 0x95, 0x8d, 0xdf, 0x81, 0xd6, 0x4d, 0x19, 0x63, 0x4b, 0x09,
	0xdf, 0x27, 0x08, 0xc4, 0xc7, 0x6c, 0x00, 0x0e, 0x8b, 0x7d, 0x96, 0xcc, 0x92, 0x45, 0x2a, 0x9b,
	0x81, 0x4f, 0xd8, 0xf0, 0x40, 0x6a, 0x23, 0x57, 0xd9, 0xbf, 0x59, 0xb2, 0x18, 0xc9, 0xc1, 0x81,
	0x36, 0x72, 0x35, 0xff, 0x49, 0xd8, 0xa4, 0xe7, 0x12, 0x1c, 0xda, 0x00, 0xfc, 0x91, 0xa5, 0xa1,
	0xf2, 0xd1, 0xe4, 0xe6, 0xf9, 0x5e, 0x74, 0xe1, 0x9f, 0xa6, 0xb4, 0xb0, 0x5b, 0x6b, 0x27, 0x11,
	0x49, 0xd6, 0x1a, 0xfe, 0xc4, 0xc6, 0x01, 0xc0, 0x2a, 0x32, 0x15, 0x04, 0xd2, 0x95, 0x53, 0x56,
	0x5b, 0x0c, 0x31, 0x29, 0x95, 0xbc, 0x66, 0x5f, 0x57, 0xf4, 0x51, 0x13, 0x3e, 0x65, 0x43, 0xf0,
	0x1e, 0x7d, 0xc8, 0xd2, 0x59, 0xba, 0x18, 0xc9, 0x76, 0xe2, 0x6b, 0xc6, 0xe2, 0x4f, 0xed, 0x34,
	0xe9, 0xec, 0x7f, 0xcc, 0x16, 0xa2, 0x77, 0x98, 0xee, 0xf0, 0xa2, 0x6e, 0x7e, 0x22, 0x4d, 0x06,
	0x6d, 0xb8, 0x16, 0x97, 0xa3, 0xe8, 0xf0, 0xa6, 0x49, 0x6f, 0x87, 0x51, 0xf6, 0xf2, 0x1b, 0x00,
	0x00, 0xff, 0xff, 0x1b, 0x21, 0x1f, 0x89, 0xcb, 0x01, 0x00, 0x00,
}
