// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/usermanager/v1/usermanager.proto

/*
Package usermanager_proto is a generated protocol buffer package.

It is generated from these files:
	proto/usermanager/v1/usermanager.proto

It has these top-level messages:
	GetKeySetRequest
	CreateUserRequest
	UpdateUserRequest
	BatchCreateUserRequest
	BatchCreateUserResponse
	BatchUpdateUserRequest
	BatchUpdateUserResponse
*/
package usermanager_proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"
import google_protobuf1 "google.golang.org/genproto/protobuf/field_mask"
import keytransparency_v1_proto "github.com/google/keytransparency/core/proto/keytransparency_v1_proto"
import keymaster_proto "github.com/google/keytransparency/core/proto/keymaster_proto"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// GetKeySetsRequest requests the keyset of a domain_id/app_id
type GetKeySetRequest struct {
	// domain_id identifies the domain.
	DomainId string `protobuf:"bytes,1,opt,name=domain_id,json=domainId" json:"domain_id,omitempty"`
	// app_id identifies the application.
	AppId string `protobuf:"bytes,2,opt,name=app_id,json=appId" json:"app_id,omitempty"`
}

func (m *GetKeySetRequest) Reset()                    { *m = GetKeySetRequest{} }
func (m *GetKeySetRequest) String() string            { return proto.CompactTextString(m) }
func (*GetKeySetRequest) ProtoMessage()               {}
func (*GetKeySetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *GetKeySetRequest) GetDomainId() string {
	if m != nil {
		return m.DomainId
	}
	return ""
}

func (m *GetKeySetRequest) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

// CreateUserRequest specifies the information with which a new user should be initialized.
// New users will be signed with the current active key.
// It is the responsibility of authorized callers to verify that domain_id/app_id/user_id is correct.
type CreateUserRequest struct {
	// user is the user to create.
	User *keytransparency_v1_proto.User `protobuf:"bytes,2,opt,name=user" json:"user,omitempty"`
	// add_signing_keys specifies whether to add this service's signing keys to the set of authorized_keys.
	// This must be set to true if any further operations from this API are meant to succeed.
	// If set to false, there must be at least one key in authorized_keys.
	AddSigningKeys bool `protobuf:"varint,7,opt,name=add_signing_keys,json=addSigningKeys" json:"add_signing_keys,omitempty"`
}

func (m *CreateUserRequest) Reset()                    { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()               {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CreateUserRequest) GetUser() *keytransparency_v1_proto.User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *CreateUserRequest) GetAddSigningKeys() bool {
	if m != nil {
		return m.AddSigningKeys
	}
	return false
}

// UpdateUserRequest sets the data field for the user.
// The user must have the service's current signing key in its list of
// authorized_keys in order to succeed.
type UpdateUserRequest struct {
	// user contains data which will be applied to the user.
	User *keytransparency_v1_proto.User `protobuf:"bytes,2,opt,name=user" json:"user,omitempty"`
	// update_mask specifies which fields of user to update.
	// For example: "data" or "authorized_keys"
	UpdateMask *google_protobuf1.FieldMask `protobuf:"bytes,3,opt,name=update_mask,json=updateMask" json:"update_mask,omitempty"`
}

func (m *UpdateUserRequest) Reset()                    { *m = UpdateUserRequest{} }
func (m *UpdateUserRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateUserRequest) ProtoMessage()               {}
func (*UpdateUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *UpdateUserRequest) GetUser() *keytransparency_v1_proto.User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *UpdateUserRequest) GetUpdateMask() *google_protobuf1.FieldMask {
	if m != nil {
		return m.UpdateMask
	}
	return nil
}

// BatchCreateUserRequest creates multiple users all at once.
type BatchCreateUserRequest struct {
	// domain_id identifies the domain.
	DomainId string `protobuf:"bytes,1,opt,name=domain_id,json=domainId" json:"domain_id,omitempty"`
	// app_id identifies the application.
	AppId string `protobuf:"bytes,2,opt,name=app_id,json=appId" json:"app_id,omitempty"`
	// users is the set of users to create.
	Users []*keytransparency_v1_proto.User `protobuf:"bytes,3,rep,name=users" json:"users,omitempty"`
	// add_signing_keys specifies whether to add this service's signing_keys to the set of authorized_keys.
	// This must be set to true if any further operations from this API are meant to succeed.
	// If set to false, there must be at least one key in authorized_keys.
	AddSigningKeys bool `protobuf:"varint,4,opt,name=add_signing_keys,json=addSigningKeys" json:"add_signing_keys,omitempty"`
}

func (m *BatchCreateUserRequest) Reset()                    { *m = BatchCreateUserRequest{} }
func (m *BatchCreateUserRequest) String() string            { return proto.CompactTextString(m) }
func (*BatchCreateUserRequest) ProtoMessage()               {}
func (*BatchCreateUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *BatchCreateUserRequest) GetDomainId() string {
	if m != nil {
		return m.DomainId
	}
	return ""
}

func (m *BatchCreateUserRequest) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *BatchCreateUserRequest) GetUsers() []*keytransparency_v1_proto.User {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *BatchCreateUserRequest) GetAddSigningKeys() bool {
	if m != nil {
		return m.AddSigningKeys
	}
	return false
}

// BatchCreateUserRequest creates multiple users at once.
type BatchCreateUserResponse struct {
	// users returns the list of created users.
	Users []*keytransparency_v1_proto.User `protobuf:"bytes,2,rep,name=users" json:"users,omitempty"`
}

func (m *BatchCreateUserResponse) Reset()                    { *m = BatchCreateUserResponse{} }
func (m *BatchCreateUserResponse) String() string            { return proto.CompactTextString(m) }
func (*BatchCreateUserResponse) ProtoMessage()               {}
func (*BatchCreateUserResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *BatchCreateUserResponse) GetUsers() []*keytransparency_v1_proto.User {
	if m != nil {
		return m.Users
	}
	return nil
}

// BatchUpdateUserRequest creates multiple users all at once.
type BatchUpdateUserRequest struct {
	// domain_id identifies the domain.
	DomainId string `protobuf:"bytes,1,opt,name=domain_id,json=domainId" json:"domain_id,omitempty"`
	// app_id identifies the application.
	AppId string `protobuf:"bytes,2,opt,name=app_id,json=appId" json:"app_id,omitempty"`
	// users is the set of users to create.
	Users []*keytransparency_v1_proto.User `protobuf:"bytes,3,rep,name=users" json:"users,omitempty"`
	// update_mask specifies which fields of user to update.
	// For example: "data" or "authorized_keys"
	UpdateMask *google_protobuf1.FieldMask `protobuf:"bytes,4,opt,name=update_mask,json=updateMask" json:"update_mask,omitempty"`
}

func (m *BatchUpdateUserRequest) Reset()                    { *m = BatchUpdateUserRequest{} }
func (m *BatchUpdateUserRequest) String() string            { return proto.CompactTextString(m) }
func (*BatchUpdateUserRequest) ProtoMessage()               {}
func (*BatchUpdateUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *BatchUpdateUserRequest) GetDomainId() string {
	if m != nil {
		return m.DomainId
	}
	return ""
}

func (m *BatchUpdateUserRequest) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *BatchUpdateUserRequest) GetUsers() []*keytransparency_v1_proto.User {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *BatchUpdateUserRequest) GetUpdateMask() *google_protobuf1.FieldMask {
	if m != nil {
		return m.UpdateMask
	}
	return nil
}

// BatchUpdateUserRequest creates multiple users at once.
type BatchUpdateUserResponse struct {
	// users returns the list of created users.
	Users []*keytransparency_v1_proto.User `protobuf:"bytes,2,rep,name=users" json:"users,omitempty"`
}

func (m *BatchUpdateUserResponse) Reset()                    { *m = BatchUpdateUserResponse{} }
func (m *BatchUpdateUserResponse) String() string            { return proto.CompactTextString(m) }
func (*BatchUpdateUserResponse) ProtoMessage()               {}
func (*BatchUpdateUserResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *BatchUpdateUserResponse) GetUsers() []*keytransparency_v1_proto.User {
	if m != nil {
		return m.Users
	}
	return nil
}

func init() {
	proto.RegisterType((*GetKeySetRequest)(nil), "usermanager.v1.GetKeySetRequest")
	proto.RegisterType((*CreateUserRequest)(nil), "usermanager.v1.CreateUserRequest")
	proto.RegisterType((*UpdateUserRequest)(nil), "usermanager.v1.UpdateUserRequest")
	proto.RegisterType((*BatchCreateUserRequest)(nil), "usermanager.v1.BatchCreateUserRequest")
	proto.RegisterType((*BatchCreateUserResponse)(nil), "usermanager.v1.BatchCreateUserResponse")
	proto.RegisterType((*BatchUpdateUserRequest)(nil), "usermanager.v1.BatchUpdateUserRequest")
	proto.RegisterType((*BatchUpdateUserResponse)(nil), "usermanager.v1.BatchUpdateUserResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for UserManagerService service

type UserManagerServiceClient interface {
	// GetKeySet returns a list of public keys (a keyset) that corresponds to the signing keys
	// this service has for a given domain and app.
	GetKeySet(ctx context.Context, in *GetKeySetRequest, opts ...grpc.CallOption) (*keymaster_proto.KeySet, error)
	// CreateUser creates a new user and initializes it.
	// If the user already exists, this operation will fail.
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*keytransparency_v1_proto.User, error)
	// UpdateUserData sets the public key for an user.
	UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*keytransparency_v1_proto.User, error)
	// BatchCreateUser creates a set of new users.
	BatchCreateUser(ctx context.Context, in *BatchCreateUserRequest, opts ...grpc.CallOption) (*keytransparency_v1_proto.User, error)
	// BatchUpdateUser updates a set of users.
	BatchUpdateUser(ctx context.Context, in *BatchUpdateUserRequest, opts ...grpc.CallOption) (*keytransparency_v1_proto.User, error)
}

type userManagerServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserManagerServiceClient(cc *grpc.ClientConn) UserManagerServiceClient {
	return &userManagerServiceClient{cc}
}

func (c *userManagerServiceClient) GetKeySet(ctx context.Context, in *GetKeySetRequest, opts ...grpc.CallOption) (*keymaster_proto.KeySet, error) {
	out := new(keymaster_proto.KeySet)
	err := grpc.Invoke(ctx, "/usermanager.v1.UserManagerService/GetKeySet", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userManagerServiceClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*keytransparency_v1_proto.User, error) {
	out := new(keytransparency_v1_proto.User)
	err := grpc.Invoke(ctx, "/usermanager.v1.UserManagerService/CreateUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userManagerServiceClient) UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*keytransparency_v1_proto.User, error) {
	out := new(keytransparency_v1_proto.User)
	err := grpc.Invoke(ctx, "/usermanager.v1.UserManagerService/UpdateUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userManagerServiceClient) BatchCreateUser(ctx context.Context, in *BatchCreateUserRequest, opts ...grpc.CallOption) (*keytransparency_v1_proto.User, error) {
	out := new(keytransparency_v1_proto.User)
	err := grpc.Invoke(ctx, "/usermanager.v1.UserManagerService/BatchCreateUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userManagerServiceClient) BatchUpdateUser(ctx context.Context, in *BatchUpdateUserRequest, opts ...grpc.CallOption) (*keytransparency_v1_proto.User, error) {
	out := new(keytransparency_v1_proto.User)
	err := grpc.Invoke(ctx, "/usermanager.v1.UserManagerService/BatchUpdateUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for UserManagerService service

type UserManagerServiceServer interface {
	// GetKeySet returns a list of public keys (a keyset) that corresponds to the signing keys
	// this service has for a given domain and app.
	GetKeySet(context.Context, *GetKeySetRequest) (*keymaster_proto.KeySet, error)
	// CreateUser creates a new user and initializes it.
	// If the user already exists, this operation will fail.
	CreateUser(context.Context, *CreateUserRequest) (*keytransparency_v1_proto.User, error)
	// UpdateUserData sets the public key for an user.
	UpdateUser(context.Context, *UpdateUserRequest) (*keytransparency_v1_proto.User, error)
	// BatchCreateUser creates a set of new users.
	BatchCreateUser(context.Context, *BatchCreateUserRequest) (*keytransparency_v1_proto.User, error)
	// BatchUpdateUser updates a set of users.
	BatchUpdateUser(context.Context, *BatchUpdateUserRequest) (*keytransparency_v1_proto.User, error)
}

func RegisterUserManagerServiceServer(s *grpc.Server, srv UserManagerServiceServer) {
	s.RegisterService(&_UserManagerService_serviceDesc, srv)
}

func _UserManagerService_GetKeySet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetKeySetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserManagerServiceServer).GetKeySet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/usermanager.v1.UserManagerService/GetKeySet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserManagerServiceServer).GetKeySet(ctx, req.(*GetKeySetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserManagerService_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserManagerServiceServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/usermanager.v1.UserManagerService/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserManagerServiceServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserManagerService_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserManagerServiceServer).UpdateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/usermanager.v1.UserManagerService/UpdateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserManagerServiceServer).UpdateUser(ctx, req.(*UpdateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserManagerService_BatchCreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchCreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserManagerServiceServer).BatchCreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/usermanager.v1.UserManagerService/BatchCreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserManagerServiceServer).BatchCreateUser(ctx, req.(*BatchCreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserManagerService_BatchUpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchUpdateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserManagerServiceServer).BatchUpdateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/usermanager.v1.UserManagerService/BatchUpdateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserManagerServiceServer).BatchUpdateUser(ctx, req.(*BatchUpdateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserManagerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "usermanager.v1.UserManagerService",
	HandlerType: (*UserManagerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetKeySet",
			Handler:    _UserManagerService_GetKeySet_Handler,
		},
		{
			MethodName: "CreateUser",
			Handler:    _UserManagerService_CreateUser_Handler,
		},
		{
			MethodName: "UpdateUser",
			Handler:    _UserManagerService_UpdateUser_Handler,
		},
		{
			MethodName: "BatchCreateUser",
			Handler:    _UserManagerService_BatchCreateUser_Handler,
		},
		{
			MethodName: "BatchUpdateUser",
			Handler:    _UserManagerService_BatchUpdateUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/usermanager/v1/usermanager.proto",
}

func init() { proto.RegisterFile("proto/usermanager/v1/usermanager.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 627 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x95, 0xdf, 0x6a, 0x13, 0x4f,
	0x14, 0xc7, 0xd9, 0x24, 0xcd, 0xaf, 0x99, 0x42, 0x7f, 0xed, 0x80, 0x36, 0x44, 0x91, 0xb8, 0x17,
	0x25, 0x54, 0x98, 0x25, 0xd1, 0x0b, 0x49, 0x29, 0x48, 0x84, 0x6a, 0x29, 0xa1, 0x92, 0x50, 0x10,
	0x2f, 0x5c, 0x26, 0xd9, 0xd3, 0xed, 0x92, 0x66, 0x77, 0x3a, 0x33, 0x09, 0x84, 0xd2, 0x1b, 0xf1,
	0xc2, 0x7b, 0x1f, 0xc1, 0x5b, 0xc1, 0x47, 0xf0, 0x11, 0xbc, 0xf0, 0x15, 0x7c, 0x10, 0x99, 0x99,
	0x4d, 0xb2, 0xee, 0x46, 0xdb, 0xd4, 0x3f, 0x37, 0x6d, 0xe6, 0xcc, 0x99, 0x3d, 0x9f, 0xf3, 0x3d,
	0x73, 0xce, 0xa0, 0x6d, 0xc6, 0x23, 0x19, 0x39, 0x23, 0x01, 0x7c, 0x48, 0x43, 0xea, 0x03, 0x77,
	0xc6, 0xf5, 0xe4, 0x92, 0x68, 0x07, 0xbc, 0x9e, 0x34, 0x8d, 0xeb, 0x95, 0xbb, 0x7e, 0x14, 0xf9,
	0x67, 0xe0, 0x50, 0x16, 0x38, 0x34, 0x0c, 0x23, 0x49, 0x65, 0x10, 0x85, 0xc2, 0x78, 0x57, 0xaa,
	0xf1, 0xae, 0x5e, 0xf5, 0x46, 0x27, 0xce, 0x49, 0x00, 0x67, 0x9e, 0x3b, 0xa4, 0x62, 0x10, 0x7b,
	0xec, 0x99, 0xb8, 0x03, 0x98, 0x48, 0x4e, 0x43, 0xc1, 0x28, 0x87, 0xb0, 0x3f, 0x71, 0xc7, 0x75,
	0xf7, 0xd7, 0x1b, 0xf1, 0xf1, 0x07, 0x33, 0xaf, 0x21, 0x15, 0x12, 0xb8, 0xbb, 0x70, 0x6d, 0x9c,
	0xed, 0x7d, 0xb4, 0xf1, 0x0c, 0xe4, 0x21, 0x4c, 0xba, 0x20, 0x3b, 0x70, 0x3e, 0x02, 0x21, 0xf1,
	0x1d, 0x54, 0xf2, 0xa2, 0x21, 0x0d, 0x42, 0x37, 0xf0, 0xca, 0x56, 0xd5, 0xaa, 0x95, 0x3a, 0xab,
	0xc6, 0x70, 0xe0, 0xe1, 0x5b, 0xa8, 0x48, 0x19, 0x53, 0x3b, 0x39, 0xbd, 0xb3, 0x42, 0x19, 0x3b,
	0xf0, 0xec, 0x73, 0xb4, 0xf9, 0x94, 0x03, 0x95, 0x70, 0x2c, 0x80, 0x4f, 0x3f, 0xd4, 0x40, 0x05,
	0x25, 0x8d, 0xf6, 0x5c, 0x6b, 0xdc, 0x23, 0x29, 0x70, 0x32, 0xae, 0x1b, 0x0a, 0xa2, 0x0f, 0x69,
	0x5f, 0x5c, 0x43, 0x1b, 0xd4, 0xf3, 0x5c, 0x11, 0xf8, 0x61, 0x10, 0xfa, 0xee, 0x00, 0x26, 0xa2,
	0xfc, 0x5f, 0xd5, 0xaa, 0xad, 0x76, 0xd6, 0xa9, 0xe7, 0x75, 0x8d, 0xf9, 0x10, 0x26, 0xc2, 0x7e,
	0x6b, 0xa1, 0xcd, 0x63, 0xe6, 0xfd, 0x81, 0x98, 0xbb, 0x68, 0x6d, 0xa4, 0x3f, 0xa4, 0xab, 0x50,
	0xce, 0xeb, 0xa3, 0x15, 0x62, 0x0a, 0x45, 0xa6, 0x85, 0x22, 0xfb, 0xaa, 0x50, 0x6d, 0x2a, 0x06,
	0x1d, 0x64, 0xdc, 0xd5, 0x6f, 0xfb, 0xa3, 0x85, 0x6e, 0xb7, 0xa8, 0xec, 0x9f, 0x66, 0xf3, 0xbf,
	0x81, 0x90, 0xf8, 0x11, 0x5a, 0x51, 0x4c, 0xa2, 0x9c, 0xaf, 0xe6, 0xaf, 0x91, 0x80, 0x71, 0x5e,
	0xa8, 0x5a, 0x61, 0xa1, 0x6a, 0x47, 0x68, 0x2b, 0x43, 0x2b, 0x58, 0x14, 0x0a, 0x98, 0x87, 0xce,
	0x2d, 0x11, 0xda, 0xfe, 0x3c, 0xcd, 0x3f, 0x5b, 0x8b, 0x7f, 0x97, 0x7f, 0xaa, 0x82, 0x85, 0xa5,
	0x2a, 0x38, 0x95, 0x24, 0x99, 0xc0, 0xef, 0x48, 0xd2, 0xf8, 0x52, 0x44, 0x58, 0xad, 0xdb, 0x66,
	0x26, 0x74, 0x81, 0x8f, 0x83, 0x3e, 0xe0, 0x77, 0x16, 0x2a, 0xcd, 0x9a, 0x0d, 0x57, 0xc9, 0x8f,
	0x63, 0x83, 0xa4, 0xfb, 0xb0, 0xb2, 0x45, 0x66, 0x3d, 0x1b, 0x07, 0x31, 0xfb, 0xf6, 0x93, 0x37,
	0x5f, 0xbf, 0xbd, 0xcf, 0x35, 0xf1, 0xe3, 0xf4, 0x6c, 0x32, 0xe2, 0x0a, 0xe7, 0x62, 0x26, 0xfb,
	0xa5, 0x43, 0x19, 0x13, 0xce, 0x85, 0x91, 0xfa, 0x52, 0x4d, 0x01, 0x01, 0x12, 0x7f, 0xb2, 0x10,
	0x9a, 0xdf, 0x00, 0x7c, 0x3f, 0xcd, 0x92, 0xb9, 0xcb, 0x95, 0x2b, 0x52, 0xb7, 0x5f, 0x6b, 0xa6,
	0x97, 0xf6, 0x8b, 0x9f, 0x32, 0x29, 0x3b, 0xc9, 0x80, 0x69, 0xeb, 0x94, 0x4e, 0xcb, 0x17, 0xdb,
	0xd4, 0x1f, 0x65, 0x6c, 0x9a, 0x1e, 0x55, 0xc4, 0xf3, 0x02, 0x65, 0x89, 0x33, 0xb7, 0xef, 0xba,
	0xc4, 0x8d, 0xbf, 0x45, 0xfc, 0xc1, 0x42, 0xff, 0xa7, 0x5a, 0x0d, 0x6f, 0xa7, 0xb1, 0x17, 0x4f,
	0x8e, 0x2b, 0xd9, 0x9f, 0x6b, 0xf6, 0x96, 0xbd, 0xb7, 0xf4, 0x0d, 0x68, 0x26, 0x22, 0x36, 0xad,
	0x9d, 0x39, 0x65, 0x42, 0xdc, 0xc5, 0x94, 0xcb, 0x2b, 0x1c, 0x53, 0x36, 0x6e, 0x4a, 0x69, 0x22,
	0x36, 0xad, 0x9d, 0xd6, 0xd1, 0xab, 0xb6, 0x1f, 0xc8, 0xd3, 0x51, 0x8f, 0xf4, 0xa3, 0xa1, 0x13,
	0xbf, 0xa0, 0xa9, 0xe0, 0x4e, 0x3f, 0xe2, 0xf1, 0xb3, 0x9a, 0x8a, 0xb7, 0x9b, 0x58, 0x9a, 0xd7,
	0xaf, 0x57, 0xd4, 0xff, 0x1e, 0x7e, 0x0f, 0x00, 0x00, 0xff, 0xff, 0x7c, 0xaa, 0x5b, 0xec, 0xe4,
	0x07, 0x00, 0x00,
}
