// Code generated by protoc-gen-go. DO NOT EDIT.
// source: keytransparency_v1_service.proto

/*
Package keytransparency_v1_service is a generated protocol buffer package.

Key Transparency Service

The Key Transparency Service API consists of a map of user names to public
keys. Each user name also has a history of public keys that have been
associated with it.

It is generated from these files:
	keytransparency_v1_service.proto

It has these top-level messages:
*/
package keytransparency_v1_service

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import keytransparency_v1_types "github.com/google/keytransparency/core/proto/keytransparency_v1_types"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for KeyTransparencyService service

type KeyTransparencyServiceClient interface {
	// GetEntry returns a user's entry in the Merkle Tree.
	//
	// Entries contain signed commitments to a profile, which is also returned.
	GetEntry(ctx context.Context, in *keytransparency_v1_types.GetEntryRequest, opts ...grpc.CallOption) (*keytransparency_v1_types.GetEntryResponse, error)
	// ListEntryHistory returns a list of historic GetEntry values.
	//
	// Clients verify their account history by observing correct values for their
	// account over time.
	ListEntryHistory(ctx context.Context, in *keytransparency_v1_types.ListEntryHistoryRequest, opts ...grpc.CallOption) (*keytransparency_v1_types.ListEntryHistoryResponse, error)
	// UpdateEntry updates a user's profile.
	//
	// Returns the current user profile.
	// Clients must retry until this function returns a proof containing the desired value.
	UpdateEntry(ctx context.Context, in *keytransparency_v1_types.UpdateEntryRequest, opts ...grpc.CallOption) (*keytransparency_v1_types.UpdateEntryResponse, error)
	// GetDomainInfo returns all info tied to the specified domain.
	//
	// This API to get all necessary data needed to verify a particular
	// key-server. Data contains for instance the tree-info, like for instance the
	// log-/map-id and the corresponding public-keys.
	GetDomainInfo(ctx context.Context, in *keytransparency_v1_types.GetDomainInfoRequest, opts ...grpc.CallOption) (*keytransparency_v1_types.GetDomainInfoResponse, error)
}

type keyTransparencyServiceClient struct {
	cc *grpc.ClientConn
}

func NewKeyTransparencyServiceClient(cc *grpc.ClientConn) KeyTransparencyServiceClient {
	return &keyTransparencyServiceClient{cc}
}

func (c *keyTransparencyServiceClient) GetEntry(ctx context.Context, in *keytransparency_v1_types.GetEntryRequest, opts ...grpc.CallOption) (*keytransparency_v1_types.GetEntryResponse, error) {
	out := new(keytransparency_v1_types.GetEntryResponse)
	err := grpc.Invoke(ctx, "/keytransparency.v1.service.KeyTransparencyService/GetEntry", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyTransparencyServiceClient) ListEntryHistory(ctx context.Context, in *keytransparency_v1_types.ListEntryHistoryRequest, opts ...grpc.CallOption) (*keytransparency_v1_types.ListEntryHistoryResponse, error) {
	out := new(keytransparency_v1_types.ListEntryHistoryResponse)
	err := grpc.Invoke(ctx, "/keytransparency.v1.service.KeyTransparencyService/ListEntryHistory", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyTransparencyServiceClient) UpdateEntry(ctx context.Context, in *keytransparency_v1_types.UpdateEntryRequest, opts ...grpc.CallOption) (*keytransparency_v1_types.UpdateEntryResponse, error) {
	out := new(keytransparency_v1_types.UpdateEntryResponse)
	err := grpc.Invoke(ctx, "/keytransparency.v1.service.KeyTransparencyService/UpdateEntry", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyTransparencyServiceClient) GetDomainInfo(ctx context.Context, in *keytransparency_v1_types.GetDomainInfoRequest, opts ...grpc.CallOption) (*keytransparency_v1_types.GetDomainInfoResponse, error) {
	out := new(keytransparency_v1_types.GetDomainInfoResponse)
	err := grpc.Invoke(ctx, "/keytransparency.v1.service.KeyTransparencyService/GetDomainInfo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for KeyTransparencyService service

type KeyTransparencyServiceServer interface {
	// GetEntry returns a user's entry in the Merkle Tree.
	//
	// Entries contain signed commitments to a profile, which is also returned.
	GetEntry(context.Context, *keytransparency_v1_types.GetEntryRequest) (*keytransparency_v1_types.GetEntryResponse, error)
	// ListEntryHistory returns a list of historic GetEntry values.
	//
	// Clients verify their account history by observing correct values for their
	// account over time.
	ListEntryHistory(context.Context, *keytransparency_v1_types.ListEntryHistoryRequest) (*keytransparency_v1_types.ListEntryHistoryResponse, error)
	// UpdateEntry updates a user's profile.
	//
	// Returns the current user profile.
	// Clients must retry until this function returns a proof containing the desired value.
	UpdateEntry(context.Context, *keytransparency_v1_types.UpdateEntryRequest) (*keytransparency_v1_types.UpdateEntryResponse, error)
	// GetDomainInfo returns all info tied to the specified domain.
	//
	// This API to get all necessary data needed to verify a particular
	// key-server. Data contains for instance the tree-info, like for instance the
	// log-/map-id and the corresponding public-keys.
	GetDomainInfo(context.Context, *keytransparency_v1_types.GetDomainInfoRequest) (*keytransparency_v1_types.GetDomainInfoResponse, error)
}

func RegisterKeyTransparencyServiceServer(s *grpc.Server, srv KeyTransparencyServiceServer) {
	s.RegisterService(&_KeyTransparencyService_serviceDesc, srv)
}

func _KeyTransparencyService_GetEntry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(keytransparency_v1_types.GetEntryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyTransparencyServiceServer).GetEntry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/keytransparency.v1.service.KeyTransparencyService/GetEntry",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyTransparencyServiceServer).GetEntry(ctx, req.(*keytransparency_v1_types.GetEntryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyTransparencyService_ListEntryHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(keytransparency_v1_types.ListEntryHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyTransparencyServiceServer).ListEntryHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/keytransparency.v1.service.KeyTransparencyService/ListEntryHistory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyTransparencyServiceServer).ListEntryHistory(ctx, req.(*keytransparency_v1_types.ListEntryHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyTransparencyService_UpdateEntry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(keytransparency_v1_types.UpdateEntryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyTransparencyServiceServer).UpdateEntry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/keytransparency.v1.service.KeyTransparencyService/UpdateEntry",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyTransparencyServiceServer).UpdateEntry(ctx, req.(*keytransparency_v1_types.UpdateEntryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyTransparencyService_GetDomainInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(keytransparency_v1_types.GetDomainInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyTransparencyServiceServer).GetDomainInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/keytransparency.v1.service.KeyTransparencyService/GetDomainInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyTransparencyServiceServer).GetDomainInfo(ctx, req.(*keytransparency_v1_types.GetDomainInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _KeyTransparencyService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "keytransparency.v1.service.KeyTransparencyService",
	HandlerType: (*KeyTransparencyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetEntry",
			Handler:    _KeyTransparencyService_GetEntry_Handler,
		},
		{
			MethodName: "ListEntryHistory",
			Handler:    _KeyTransparencyService_ListEntryHistory_Handler,
		},
		{
			MethodName: "UpdateEntry",
			Handler:    _KeyTransparencyService_UpdateEntry_Handler,
		},
		{
			MethodName: "GetDomainInfo",
			Handler:    _KeyTransparencyService_GetDomainInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "keytransparency_v1_service.proto",
}

func init() { proto.RegisterFile("keytransparency_v1_service.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 343 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0x4f, 0x4b, 0x33, 0x31,
	0x10, 0x87, 0xe9, 0xcb, 0x8b, 0xc8, 0xaa, 0xa8, 0x11, 0x15, 0xb6, 0x0a, 0x62, 0x4f, 0x15, 0xdd,
	0xb0, 0xf5, 0xe6, 0x59, 0xa9, 0xa2, 0x27, 0xff, 0x9c, 0x97, 0x74, 0x77, 0xda, 0x06, 0x6d, 0x66,
	0x4d, 0xb2, 0x0b, 0x41, 0xf4, 0xe0, 0xcd, 0xb3, 0x78, 0xf5, 0x4b, 0x79, 0xf6, 0xe6, 0x07, 0x91,
	0x66, 0xb3, 0x58, 0xca, 0x56, 0xd6, 0x53, 0x0e, 0xf3, 0xcc, 0x6f, 0x9e, 0x4c, 0xe2, 0xed, 0xdc,
	0x82, 0xd1, 0x92, 0x09, 0x95, 0x32, 0x09, 0x22, 0x36, 0x51, 0x1e, 0x46, 0x0a, 0x64, 0xce, 0x63,
	0x08, 0x52, 0x89, 0x1a, 0x89, 0x3f, 0x45, 0x04, 0x79, 0x18, 0x38, 0xc2, 0x4f, 0x06, 0x5c, 0x0f,
	0xb3, 0x5e, 0x10, 0xe3, 0x88, 0x0e, 0x10, 0x07, 0x77, 0x40, 0xa7, 0x68, 0x1a, 0xa3, 0x04, 0x6a,
	0x93, 0x68, 0xc5, 0x28, 0x6d, 0x52, 0x50, 0x33, 0x0b, 0x85, 0x81, 0xbf, 0xe5, 0xa2, 0x59, 0xca,
	0x29, 0x13, 0x02, 0x35, 0xd3, 0x1c, 0x85, 0xab, 0x76, 0x3e, 0xff, 0x7b, 0x1b, 0xe7, 0x60, 0xae,
	0x27, 0x02, 0xae, 0x0a, 0x3d, 0xf2, 0xe4, 0xcd, 0x77, 0x41, 0x9f, 0x08, 0x2d, 0x0d, 0x69, 0x07,
	0x15, 0xf7, 0x28, 0xa6, 0x94, 0xcc, 0x25, 0xdc, 0x67, 0xa0, 0xb4, 0xbf, 0x57, 0x07, 0x55, 0x29,
	0x0a, 0x05, 0xbb, 0xcd, 0xe7, 0x8f, 0xaf, 0xd7, 0x7f, 0xeb, 0x64, 0x8d, 0xe6, 0x21, 0xcd, 0x14,
	0x48, 0x45, 0x1f, 0xc6, 0x47, 0xc4, 0x93, 0x47, 0xf2, 0xde, 0xf0, 0x56, 0x2e, 0xb8, 0x2a, 0x5a,
	0x4e, 0xb9, 0xd2, 0x28, 0x0d, 0x09, 0x67, 0xa7, 0x4f, 0xb3, 0xa5, 0x50, 0xe7, 0x2f, 0x2d, 0x4e,
	0xac, 0x65, 0xc5, 0xb6, 0x49, 0xb3, 0x42, 0x8c, 0x0e, 0x9d, 0xcb, 0x5b, 0xc3, 0x5b, 0xb8, 0x49,
	0x13, 0xa6, 0xa1, 0x58, 0xd2, 0xfe, 0xec, 0x41, 0x13, 0x58, 0xa9, 0x75, 0x50, 0x93, 0x76, 0x46,
	0x6d, 0x6b, 0xd4, 0xf2, 0xab, 0x56, 0x75, 0xb4, 0x08, 0x63, 0x36, 0xca, 0x6c, 0x1f, 0x79, 0x69,
	0x78, 0x4b, 0x5d, 0xd0, 0xc7, 0x38, 0x62, 0x5c, 0x9c, 0x89, 0x3e, 0x92, 0xe0, 0xd7, 0x37, 0xf9,
	0x01, 0x4b, 0x37, 0x5a, 0x9b, 0x77, 0x76, 0x9b, 0xd6, 0x6e, 0x95, 0x2c, 0x8f, 0xed, 0x12, 0x5b,
	0xa7, 0x5c, 0xf4, 0xb1, 0x37, 0x67, 0xbf, 0xd9, 0xe1, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0xa0,
	0xc2, 0x1d, 0xdb, 0x2a, 0x03, 0x00, 0x00,
}
