// Code generated by protoc-gen-go.
// source: keytransparency_v1_service.proto
// DO NOT EDIT!

/*
Package keytransparency_v1_service is a generated protocol buffer package.

Key Transparency Service

The Key Transparency Service API consists of a map of user names to public
keys. Each user name also has a history of public keys that have been
associated with it.

It is generated from these files:
	keytransparency_v1_service.proto

It has these top-level messages:
*/
package keytransparency_v1_service

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import keytransparency_v1_types "github.com/google/keytransparency/core/proto/keytransparency_v1_types"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for KeyTransparencyService service

type KeyTransparencyServiceClient interface {
	// GetEntry returns a user's entry in the Merkle Tree.
	//
	// Entries contain signed commitments to a profile, which is also returned.
	GetEntry(ctx context.Context, in *keytransparency_v1_types.GetEntryRequest, opts ...grpc.CallOption) (*keytransparency_v1_types.GetEntryResponse, error)
	// ListEntryHistory returns a list of historic GetEntry values.
	//
	// Clients verify their account history by observing correct values for their
	// account over time.
	ListEntryHistory(ctx context.Context, in *keytransparency_v1_types.ListEntryHistoryRequest, opts ...grpc.CallOption) (*keytransparency_v1_types.ListEntryHistoryResponse, error)
	// UpdateEntry updates a user's profile.
	//
	// Returns the current user profile.
	// Clients must retry until this function returns a proof containing the desired value.
	UpdateEntry(ctx context.Context, in *keytransparency_v1_types.UpdateEntryRequest, opts ...grpc.CallOption) (*keytransparency_v1_types.UpdateEntryResponse, error)
	// GetMutations returns a list of mutations paged by epoch or mutation sequence
	// number.
	//
	// Returns a list of mutations and their inclusion proofs along with the epoch
	// signed map root.
	GetMutations(ctx context.Context, in *keytransparency_v1_types.GetMutationsRequest, opts ...grpc.CallOption) (*keytransparency_v1_types.GetMutationsResponse, error)
	// GetMutationsStream is a streaming API similar to GetMutations.
	//
	// Returns a list of mutations and their inclusion proofs along with the epoch
	// signed map root.
	GetMutationsStream(ctx context.Context, in *keytransparency_v1_types.GetMutationsRequest, opts ...grpc.CallOption) (KeyTransparencyService_GetMutationsStreamClient, error)
}

type keyTransparencyServiceClient struct {
	cc *grpc.ClientConn
}

func NewKeyTransparencyServiceClient(cc *grpc.ClientConn) KeyTransparencyServiceClient {
	return &keyTransparencyServiceClient{cc}
}

func (c *keyTransparencyServiceClient) GetEntry(ctx context.Context, in *keytransparency_v1_types.GetEntryRequest, opts ...grpc.CallOption) (*keytransparency_v1_types.GetEntryResponse, error) {
	out := new(keytransparency_v1_types.GetEntryResponse)
	err := grpc.Invoke(ctx, "/keytransparency.v1.service.KeyTransparencyService/GetEntry", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyTransparencyServiceClient) ListEntryHistory(ctx context.Context, in *keytransparency_v1_types.ListEntryHistoryRequest, opts ...grpc.CallOption) (*keytransparency_v1_types.ListEntryHistoryResponse, error) {
	out := new(keytransparency_v1_types.ListEntryHistoryResponse)
	err := grpc.Invoke(ctx, "/keytransparency.v1.service.KeyTransparencyService/ListEntryHistory", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyTransparencyServiceClient) UpdateEntry(ctx context.Context, in *keytransparency_v1_types.UpdateEntryRequest, opts ...grpc.CallOption) (*keytransparency_v1_types.UpdateEntryResponse, error) {
	out := new(keytransparency_v1_types.UpdateEntryResponse)
	err := grpc.Invoke(ctx, "/keytransparency.v1.service.KeyTransparencyService/UpdateEntry", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyTransparencyServiceClient) GetMutations(ctx context.Context, in *keytransparency_v1_types.GetMutationsRequest, opts ...grpc.CallOption) (*keytransparency_v1_types.GetMutationsResponse, error) {
	out := new(keytransparency_v1_types.GetMutationsResponse)
	err := grpc.Invoke(ctx, "/keytransparency.v1.service.KeyTransparencyService/GetMutations", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyTransparencyServiceClient) GetMutationsStream(ctx context.Context, in *keytransparency_v1_types.GetMutationsRequest, opts ...grpc.CallOption) (KeyTransparencyService_GetMutationsStreamClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_KeyTransparencyService_serviceDesc.Streams[0], c.cc, "/keytransparency.v1.service.KeyTransparencyService/GetMutationsStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &keyTransparencyServiceGetMutationsStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type KeyTransparencyService_GetMutationsStreamClient interface {
	Recv() (*keytransparency_v1_types.GetMutationsResponse, error)
	grpc.ClientStream
}

type keyTransparencyServiceGetMutationsStreamClient struct {
	grpc.ClientStream
}

func (x *keyTransparencyServiceGetMutationsStreamClient) Recv() (*keytransparency_v1_types.GetMutationsResponse, error) {
	m := new(keytransparency_v1_types.GetMutationsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for KeyTransparencyService service

type KeyTransparencyServiceServer interface {
	// GetEntry returns a user's entry in the Merkle Tree.
	//
	// Entries contain signed commitments to a profile, which is also returned.
	GetEntry(context.Context, *keytransparency_v1_types.GetEntryRequest) (*keytransparency_v1_types.GetEntryResponse, error)
	// ListEntryHistory returns a list of historic GetEntry values.
	//
	// Clients verify their account history by observing correct values for their
	// account over time.
	ListEntryHistory(context.Context, *keytransparency_v1_types.ListEntryHistoryRequest) (*keytransparency_v1_types.ListEntryHistoryResponse, error)
	// UpdateEntry updates a user's profile.
	//
	// Returns the current user profile.
	// Clients must retry until this function returns a proof containing the desired value.
	UpdateEntry(context.Context, *keytransparency_v1_types.UpdateEntryRequest) (*keytransparency_v1_types.UpdateEntryResponse, error)
	// GetMutations returns a list of mutations paged by epoch or mutation sequence
	// number.
	//
	// Returns a list of mutations and their inclusion proofs along with the epoch
	// signed map root.
	GetMutations(context.Context, *keytransparency_v1_types.GetMutationsRequest) (*keytransparency_v1_types.GetMutationsResponse, error)
	// GetMutationsStream is a streaming API similar to GetMutations.
	//
	// Returns a list of mutations and their inclusion proofs along with the epoch
	// signed map root.
	GetMutationsStream(*keytransparency_v1_types.GetMutationsRequest, KeyTransparencyService_GetMutationsStreamServer) error
}

func RegisterKeyTransparencyServiceServer(s *grpc.Server, srv KeyTransparencyServiceServer) {
	s.RegisterService(&_KeyTransparencyService_serviceDesc, srv)
}

func _KeyTransparencyService_GetEntry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(keytransparency_v1_types.GetEntryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyTransparencyServiceServer).GetEntry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/keytransparency.v1.service.KeyTransparencyService/GetEntry",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyTransparencyServiceServer).GetEntry(ctx, req.(*keytransparency_v1_types.GetEntryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyTransparencyService_ListEntryHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(keytransparency_v1_types.ListEntryHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyTransparencyServiceServer).ListEntryHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/keytransparency.v1.service.KeyTransparencyService/ListEntryHistory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyTransparencyServiceServer).ListEntryHistory(ctx, req.(*keytransparency_v1_types.ListEntryHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyTransparencyService_UpdateEntry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(keytransparency_v1_types.UpdateEntryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyTransparencyServiceServer).UpdateEntry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/keytransparency.v1.service.KeyTransparencyService/UpdateEntry",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyTransparencyServiceServer).UpdateEntry(ctx, req.(*keytransparency_v1_types.UpdateEntryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyTransparencyService_GetMutations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(keytransparency_v1_types.GetMutationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyTransparencyServiceServer).GetMutations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/keytransparency.v1.service.KeyTransparencyService/GetMutations",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyTransparencyServiceServer).GetMutations(ctx, req.(*keytransparency_v1_types.GetMutationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyTransparencyService_GetMutationsStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(keytransparency_v1_types.GetMutationsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(KeyTransparencyServiceServer).GetMutationsStream(m, &keyTransparencyServiceGetMutationsStreamServer{stream})
}

type KeyTransparencyService_GetMutationsStreamServer interface {
	Send(*keytransparency_v1_types.GetMutationsResponse) error
	grpc.ServerStream
}

type keyTransparencyServiceGetMutationsStreamServer struct {
	grpc.ServerStream
}

func (x *keyTransparencyServiceGetMutationsStreamServer) Send(m *keytransparency_v1_types.GetMutationsResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _KeyTransparencyService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "keytransparency.v1.service.KeyTransparencyService",
	HandlerType: (*KeyTransparencyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetEntry",
			Handler:    _KeyTransparencyService_GetEntry_Handler,
		},
		{
			MethodName: "ListEntryHistory",
			Handler:    _KeyTransparencyService_ListEntryHistory_Handler,
		},
		{
			MethodName: "UpdateEntry",
			Handler:    _KeyTransparencyService_UpdateEntry_Handler,
		},
		{
			MethodName: "GetMutations",
			Handler:    _KeyTransparencyService_GetMutations_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetMutationsStream",
			Handler:       _KeyTransparencyService_GetMutationsStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "keytransparency_v1_service.proto",
}

func init() { proto.RegisterFile("keytransparency_v1_service.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 368 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x93, 0x31, 0x4b, 0xc3, 0x40,
	0x14, 0xc7, 0x89, 0x43, 0x91, 0xd8, 0x41, 0x4e, 0x74, 0x48, 0x2b, 0x68, 0x3b, 0x55, 0x6c, 0xce,
	0xd4, 0xcd, 0x5d, 0x2a, 0xa8, 0x8b, 0xd5, 0x39, 0x5c, 0xd3, 0x47, 0x1a, 0x6a, 0xef, 0xe2, 0xdd,
	0x4b, 0x20, 0x94, 0x3a, 0x38, 0xb9, 0x8a, 0xb8, 0x8a, 0xdf, 0xc9, 0xaf, 0xe0, 0x07, 0x91, 0x5e,
	0x2e, 0x52, 0x4a, 0x22, 0x75, 0x70, 0xca, 0xf0, 0x7e, 0xef, 0xff, 0x7e, 0x79, 0x8f, 0xb3, 0x0f,
	0x26, 0x90, 0xa1, 0x64, 0x5c, 0xc5, 0x4c, 0x02, 0x0f, 0x32, 0x3f, 0xf5, 0x7c, 0x05, 0x32, 0x8d,
	0x02, 0x70, 0x63, 0x29, 0x50, 0x10, 0x67, 0x85, 0x70, 0x53, 0xcf, 0x35, 0x84, 0x33, 0x0a, 0x23,
	0x1c, 0x27, 0x43, 0x37, 0x10, 0x53, 0x1a, 0x0a, 0x11, 0xde, 0x03, 0x5d, 0xa1, 0x69, 0x20, 0x24,
	0x50, 0x9d, 0x44, 0x4b, 0x46, 0x61, 0x16, 0x83, 0xaa, 0x2c, 0xe4, 0x06, 0x4e, 0xd3, 0x44, 0xb3,
	0x38, 0xa2, 0x8c, 0x73, 0x81, 0x0c, 0x23, 0xc1, 0x4d, 0xb5, 0xf7, 0x5c, 0xb3, 0xf7, 0x2e, 0x21,
	0xbb, 0x5d, 0x0a, 0x18, 0xe4, 0x7a, 0xe4, 0xd1, 0xde, 0xec, 0x03, 0x9e, 0x73, 0x94, 0x19, 0xe9,
	0xb8, 0x25, 0xff, 0x91, 0x4f, 0x29, 0x98, 0x1b, 0x78, 0x48, 0x40, 0xa1, 0x73, 0xb4, 0x0e, 0xaa,
	0x62, 0xc1, 0x15, 0xb4, 0x1a, 0x4f, 0x9f, 0x5f, 0xaf, 0x1b, 0xbb, 0x64, 0x87, 0xa6, 0x1e, 0x4d,
	0x14, 0x48, 0x45, 0x67, 0x8b, 0x8f, 0x1f, 0x8d, 0xe6, 0xe4, 0xdd, 0xb2, 0xb7, 0xaf, 0x22, 0x95,
	0xb7, 0x5c, 0x44, 0x0a, 0x85, 0xcc, 0x88, 0x57, 0x9d, 0xbe, 0xca, 0x16, 0x42, 0xbd, 0xbf, 0xb4,
	0x18, 0xb1, 0xb6, 0x16, 0xdb, 0x27, 0x8d, 0x12, 0x31, 0x3a, 0x36, 0x2e, 0x6f, 0x96, 0xbd, 0x75,
	0x17, 0x8f, 0x18, 0x42, 0xbe, 0xa4, 0xe3, 0xea, 0x41, 0x4b, 0x58, 0xa1, 0xd5, 0x5d, 0x93, 0x36,
	0x46, 0x1d, 0x6d, 0xd4, 0x76, 0xca, 0x56, 0x75, 0x56, 0x87, 0x05, 0xeb, 0x27, 0xba, 0x8f, 0xbc,
	0x58, 0x76, 0xbd, 0x0f, 0x78, 0x9d, 0x98, 0x53, 0x93, 0xee, 0xaf, 0x27, 0xf9, 0xe1, 0x0a, 0x33,
	0x77, 0x5d, 0xdc, 0xa8, 0xb5, 0xb4, 0x5a, 0x93, 0x38, 0x0b, 0xb5, 0x69, 0x51, 0xa6, 0xb3, 0x98,
	0x85, 0xe0, 0xa3, 0x98, 0x00, 0x9f, 0x93, 0x0f, 0xcb, 0x26, 0xcb, 0xcd, 0x03, 0x94, 0xc0, 0xa6,
	0xff, 0x6d, 0x66, 0x96, 0x46, 0x0e, 0xab, 0xcd, 0xa8, 0xd2, 0x26, 0x27, 0xd6, 0xb0, 0xa6, 0x5f,
	0xc4, 0xe9, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0x53, 0x3a, 0xdd, 0x86, 0xd5, 0x03, 0x00, 0x00,
}
