// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/sequencer_v1_grpc/sequencer_v1_grpc.proto

/*
Package sequencer_v1_grpc is a generated protocol buffer package.

It is generated from these files:
	proto/sequencer_v1_grpc/sequencer_v1_grpc.proto

It has these top-level messages:
*/
package sequencer_v1_grpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"
import google_keytransparency_v1 "github.com/google/keytransparency/core/proto/keytransparency_v1_grpc"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for SequencerService service

type SequencerServiceClient interface {
	// GetEpochs is a streaming API that sends epoch mutations upon creation.
	//
	// Returns the mutations of a newly created epoch.
	GetEpochs(ctx context.Context, in *google_keytransparency_v1.GetEpochsRequest, opts ...grpc.CallOption) (SequencerService_GetEpochsClient, error)
}

type sequencerServiceClient struct {
	cc *grpc.ClientConn
}

func NewSequencerServiceClient(cc *grpc.ClientConn) SequencerServiceClient {
	return &sequencerServiceClient{cc}
}

func (c *sequencerServiceClient) GetEpochs(ctx context.Context, in *google_keytransparency_v1.GetEpochsRequest, opts ...grpc.CallOption) (SequencerService_GetEpochsClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_SequencerService_serviceDesc.Streams[0], c.cc, "/google.keytransparency.sequencer.v1.SequencerService/GetEpochs", opts...)
	if err != nil {
		return nil, err
	}
	x := &sequencerServiceGetEpochsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type SequencerService_GetEpochsClient interface {
	Recv() (*google_keytransparency_v1.GetEpochsResponse, error)
	grpc.ClientStream
}

type sequencerServiceGetEpochsClient struct {
	grpc.ClientStream
}

func (x *sequencerServiceGetEpochsClient) Recv() (*google_keytransparency_v1.GetEpochsResponse, error) {
	m := new(google_keytransparency_v1.GetEpochsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for SequencerService service

type SequencerServiceServer interface {
	// GetEpochs is a streaming API that sends epoch mutations upon creation.
	//
	// Returns the mutations of a newly created epoch.
	GetEpochs(*google_keytransparency_v1.GetEpochsRequest, SequencerService_GetEpochsServer) error
}

func RegisterSequencerServiceServer(s *grpc.Server, srv SequencerServiceServer) {
	s.RegisterService(&_SequencerService_serviceDesc, srv)
}

func _SequencerService_GetEpochs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(google_keytransparency_v1.GetEpochsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SequencerServiceServer).GetEpochs(m, &sequencerServiceGetEpochsServer{stream})
}

type SequencerService_GetEpochsServer interface {
	Send(*google_keytransparency_v1.GetEpochsResponse) error
	grpc.ServerStream
}

type sequencerServiceGetEpochsServer struct {
	grpc.ServerStream
}

func (x *sequencerServiceGetEpochsServer) Send(m *google_keytransparency_v1.GetEpochsResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _SequencerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "google.keytransparency.sequencer.v1.SequencerService",
	HandlerType: (*SequencerServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetEpochs",
			Handler:       _SequencerService_GetEpochs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/sequencer_v1_grpc/sequencer_v1_grpc.proto",
}

func init() { proto.RegisterFile("proto/sequencer_v1_grpc/sequencer_v1_grpc.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 232 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xd2, 0x2f, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x2f, 0x4e, 0x2d, 0x2c, 0x4d, 0xcd, 0x4b, 0x4e, 0x2d, 0x8a, 0x2f, 0x33, 0x8c, 0x4f,
	0x2f, 0x2a, 0x48, 0xc6, 0x14, 0xd1, 0x03, 0xab, 0x14, 0x52, 0x4e, 0xcf, 0xcf, 0x4f, 0xcf, 0x49,
	0xd5, 0xcb, 0x4e, 0xad, 0x2c, 0x29, 0x4a, 0xcc, 0x2b, 0x2e, 0x48, 0x2c, 0x4a, 0xcd, 0x4b, 0xae,
	0xd4, 0x83, 0xab, 0xd7, 0x2b, 0x33, 0x94, 0x92, 0x81, 0x28, 0xd2, 0x4f, 0x2c, 0xc8, 0xd4, 0x4f,
	0xcc, 0xcb, 0xcb, 0x2f, 0x49, 0x2c, 0xc9, 0xcc, 0xcf, 0x2b, 0x86, 0x18, 0x21, 0x65, 0x0d, 0xb1,
	0x13, 0xcd, 0x04, 0xb8, 0xcd, 0x38, 0xc4, 0x21, 0x9a, 0x8d, 0x66, 0x30, 0x72, 0x09, 0x04, 0xc3,
	0xec, 0x0a, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0x15, 0x6a, 0x66, 0xe4, 0xe2, 0x74, 0x4f, 0x2d,
	0x71, 0x2d, 0xc8, 0x4f, 0xce, 0x28, 0x16, 0xd2, 0xd6, 0xc3, 0xe1, 0xc6, 0x32, 0x43, 0x3d, 0xb8,
	0xaa, 0x20, 0x90, 0x19, 0xc5, 0x25, 0x52, 0x3a, 0xc4, 0x29, 0x2e, 0x2e, 0xc8, 0xcf, 0x2b, 0x4e,
	0x55, 0x92, 0x6c, 0xba, 0xfc, 0x64, 0x32, 0x93, 0xb0, 0x90, 0xa0, 0x7e, 0x99, 0xa1, 0x7e, 0x2a,
	0x58, 0xce, 0xaa, 0xb8, 0xa4, 0x28, 0x35, 0x31, 0xd7, 0x80, 0xd1, 0xc9, 0x21, 0xca, 0x2e, 0x3d,
	0xb3, 0x24, 0xa3, 0x34, 0x49, 0x2f, 0x39, 0x3f, 0x57, 0x1f, 0x1a, 0x04, 0x68, 0xc6, 0xea, 0x27,
	0xe7, 0x17, 0xa5, 0xe2, 0x0a, 0xf4, 0x24, 0x36, 0xb0, 0x84, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff,
	0x2f, 0xd7, 0xd9, 0xd2, 0x96, 0x01, 0x00, 0x00,
}
