FROM prom/prometheus

ADD --chown=nobody:nogroup ./deploy/prometheus/prometheus.yml /etc/prometheus/prometheus.yml
ADD --chown=nobody:nogroup ./deploy/prometheus/prometheus.rules /etc/prometheus/prometheus.rules

