// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/authorization_proto/authorization_proto.proto

/*
Package authorization_proto is a generated protocol buffer package.

It is generated from these files:
	proto/authorization_proto/authorization_proto.proto

It has these top-level messages:
	AuthorizationPolicy
*/
package authorization_proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Permission specifies the permission a role can take.
type Permission int32

const (
	// LOG indicates whether access to resources will be logged.
	Permission_LOG   Permission = 0
	Permission_READ  Permission = 1
	Permission_WRITE Permission = 2
)

var Permission_name = map[int32]string{
	0: "LOG",
	1: "READ",
	2: "WRITE",
}
var Permission_value = map[string]int32{
	"LOG":   0,
	"READ":  1,
	"WRITE": 2,
}

func (x Permission) String() string {
	return proto.EnumName(Permission_name, int32(x))
}
func (Permission) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// AuthorizationPolicy contains an authorization policy.
type AuthorizationPolicy struct {
	// roles is a map of roles keyed by labels used in RoleLabels.
	Roles map[string]*AuthorizationPolicy_Role `protobuf:"bytes,2,rep,name=roles" json:"roles,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// resource_to_role_labels specifies the authorization policy keyed by resource
	// map_id|app_id concatenation as a string.
	ResourceToRoleLabels map[string]*AuthorizationPolicy_RoleLabels `protobuf:"bytes,3,rep,name=resource_to_role_labels,json=resourceToRoleLabels" json:"resource_to_role_labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *AuthorizationPolicy) Reset()                    { *m = AuthorizationPolicy{} }
func (m *AuthorizationPolicy) String() string            { return proto.CompactTextString(m) }
func (*AuthorizationPolicy) ProtoMessage()               {}
func (*AuthorizationPolicy) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *AuthorizationPolicy) GetRoles() map[string]*AuthorizationPolicy_Role {
	if m != nil {
		return m.Roles
	}
	return nil
}

func (m *AuthorizationPolicy) GetResourceToRoleLabels() map[string]*AuthorizationPolicy_RoleLabels {
	if m != nil {
		return m.ResourceToRoleLabels
	}
	return nil
}

// Resource contains the resource being accessed.
type AuthorizationPolicy_Resource struct {
	// map_id contains the Key Transparency map identity for this entry.
	MapId int64 `protobuf:"varint,1,opt,name=map_id,json=mapId" json:"map_id,omitempty"`
	// app_id contains the application identity for this entry.
	AppId string `protobuf:"bytes,2,opt,name=app_id,json=appId" json:"app_id,omitempty"`
}

func (m *AuthorizationPolicy_Resource) Reset()                    { *m = AuthorizationPolicy_Resource{} }
func (m *AuthorizationPolicy_Resource) String() string            { return proto.CompactTextString(m) }
func (*AuthorizationPolicy_Resource) ProtoMessage()               {}
func (*AuthorizationPolicy_Resource) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

func (m *AuthorizationPolicy_Resource) GetMapId() int64 {
	if m != nil {
		return m.MapId
	}
	return 0
}

func (m *AuthorizationPolicy_Resource) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

// Role contains a specific identity of an authorization entry.
type AuthorizationPolicy_Role struct {
	// principals contains an application specific identifier for this entry.
	Principals []string `protobuf:"bytes,1,rep,name=principals" json:"principals,omitempty"`
	// permissions contains the set of permissions this role is granted.
	Permissions []Permission `protobuf:"varint,2,rep,packed,name=permissions,enum=authorization.proto.Permission" json:"permissions,omitempty"`
}

func (m *AuthorizationPolicy_Role) Reset()                    { *m = AuthorizationPolicy_Role{} }
func (m *AuthorizationPolicy_Role) String() string            { return proto.CompactTextString(m) }
func (*AuthorizationPolicy_Role) ProtoMessage()               {}
func (*AuthorizationPolicy_Role) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 1} }

func (m *AuthorizationPolicy_Role) GetPrincipals() []string {
	if m != nil {
		return m.Principals
	}
	return nil
}

func (m *AuthorizationPolicy_Role) GetPermissions() []Permission {
	if m != nil {
		return m.Permissions
	}
	return nil
}

// RoleLabels contains a lot of role labels identifying each role.
type AuthorizationPolicy_RoleLabels struct {
	Labels []string `protobuf:"bytes,1,rep,name=labels" json:"labels,omitempty"`
}

func (m *AuthorizationPolicy_RoleLabels) Reset()         { *m = AuthorizationPolicy_RoleLabels{} }
func (m *AuthorizationPolicy_RoleLabels) String() string { return proto.CompactTextString(m) }
func (*AuthorizationPolicy_RoleLabels) ProtoMessage()    {}
func (*AuthorizationPolicy_RoleLabels) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{0, 2}
}

func (m *AuthorizationPolicy_RoleLabels) GetLabels() []string {
	if m != nil {
		return m.Labels
	}
	return nil
}

func init() {
	proto.RegisterType((*AuthorizationPolicy)(nil), "authorization.proto.AuthorizationPolicy")
	proto.RegisterType((*AuthorizationPolicy_Resource)(nil), "authorization.proto.AuthorizationPolicy.Resource")
	proto.RegisterType((*AuthorizationPolicy_Role)(nil), "authorization.proto.AuthorizationPolicy.Role")
	proto.RegisterType((*AuthorizationPolicy_RoleLabels)(nil), "authorization.proto.AuthorizationPolicy.RoleLabels")
	proto.RegisterEnum("authorization.proto.Permission", Permission_name, Permission_value)
}

func init() {
	proto.RegisterFile("proto/authorization_proto/authorization_proto.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 401 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0x4d, 0xab, 0x9b, 0x40,
	0x14, 0xad, 0xfa, 0x4c, 0x9f, 0x37, 0x50, 0x64, 0x5e, 0x3f, 0xac, 0x8b, 0x56, 0x4a, 0x17, 0x12,
	0xa8, 0x42, 0xb2, 0x09, 0x5d, 0x35, 0x69, 0x43, 0x11, 0x02, 0x0d, 0x43, 0xa0, 0xd0, 0x8d, 0x4c,
	0xcc, 0x60, 0x86, 0xa8, 0x33, 0x8c, 0x5a, 0xb0, 0xf4, 0x2f, 0xf4, 0x3f, 0x17, 0x9d, 0xb4, 0x31,
	0x60, 0xe0, 0x65, 0xe3, 0xc7, 0xb9, 0xf7, 0x9c, 0xe3, 0x39, 0x2a, 0xcc, 0x84, 0xe4, 0x15, 0x0f,
	0x49, 0x5d, 0x1d, 0xb8, 0x64, 0xbf, 0x48, 0xc5, 0x78, 0x11, 0x5f, 0xc5, 0x82, 0xee, 0x88, 0x1e,
	0x2e, 0x46, 0x0a, 0x7c, 0xf7, 0xc7, 0x84, 0x87, 0x45, 0x1f, 0xdf, 0xf0, 0x8c, 0x25, 0x0d, 0x8a,
	0xc0, 0x94, 0x3c, 0xa3, 0xa5, 0xa3, 0x7b, 0x86, 0x3f, 0x9e, 0xce, 0x82, 0x01, 0x72, 0x30, 0x40,
	0x0c, 0x70, 0xcb, 0x5a, 0x15, 0x95, 0x6c, 0xb0, 0x52, 0x40, 0x0d, 0xbc, 0x92, 0xb4, 0xe4, 0xb5,
	0x4c, 0x68, 0x5c, 0xf1, 0xb8, 0x05, 0xe3, 0x8c, 0xec, 0x68, 0x56, 0x3a, 0x46, 0x27, 0xbe, 0x7c,
	0xbc, 0xf8, 0x49, 0x67, 0xcb, 0x5b, 0x9b, 0x75, 0x27, 0xa2, 0xbc, 0x9e, 0xcb, 0x81, 0x91, 0x3b,
	0x87, 0xfb, 0x7f, 0x14, 0xf4, 0x02, 0x46, 0x39, 0x11, 0x31, 0xdb, 0x3b, 0x9a, 0xa7, 0xf9, 0x06,
	0x36, 0x73, 0x22, 0xa2, 0x7d, 0x0b, 0x13, 0xd1, 0xc1, 0xba, 0xa7, 0xf9, 0x16, 0x36, 0x89, 0x10,
	0xd1, 0xde, 0x65, 0x70, 0xd7, 0xea, 0xa0, 0x37, 0x00, 0x42, 0xb2, 0x22, 0x61, 0x82, 0x64, 0xa5,
	0xa3, 0x79, 0x86, 0x6f, 0xe1, 0x1e, 0x82, 0x16, 0x30, 0x16, 0x54, 0xe6, 0xac, 0x2c, 0x19, 0x2f,
	0x54, 0x5b, 0xcf, 0xa6, 0x6f, 0x07, 0x03, 0x6d, 0xfe, 0xef, 0xe1, 0x3e, 0xc7, 0x7d, 0x0f, 0x70,
	0x7e, 0x64, 0xf4, 0x12, 0x46, 0xa7, 0x72, 0x94, 0xd9, 0xe9, 0xce, 0x4d, 0xd5, 0x96, 0x8a, 0x8b,
	0x6c, 0x30, 0x8e, 0xb4, 0xe9, 0x92, 0x58, 0xb8, 0xbd, 0x44, 0x9f, 0xc1, 0xfc, 0x49, 0xb2, 0x9a,
	0x76, 0x31, 0xc6, 0xd3, 0x0f, 0x37, 0xbd, 0x30, 0xac, 0xb8, 0x1f, 0xf5, 0xb9, 0xe6, 0xfe, 0x86,
	0xd7, 0x57, 0x6b, 0x1e, 0xf0, 0x8d, 0x2e, 0x7d, 0x6f, 0xfb, 0x50, 0x94, 0x74, 0xcf, 0x7d, 0x32,
	0x01, 0x38, 0xf7, 0x84, 0x9e, 0x82, 0xb1, 0xfe, 0xf6, 0xd5, 0x7e, 0x82, 0xee, 0xe1, 0x0e, 0xaf,
	0x16, 0x5f, 0x6c, 0x0d, 0x59, 0x60, 0x7e, 0xc7, 0xd1, 0x76, 0x65, 0xeb, 0xcb, 0xe5, 0x8f, 0x4f,
	0x29, 0xab, 0x0e, 0xf5, 0x2e, 0x48, 0x78, 0x1e, 0xa6, 0x9c, 0xa7, 0x19, 0x0d, 0x8f, 0xb4, 0xa9,
	0x24, 0x29, 0x4a, 0x41, 0x24, 0x2d, 0x92, 0x26, 0x4c, 0xb8, 0xa4, 0xe1, 0xd5, 0x5f, 0x63, 0x37,
	0xea, 0x4e, 0xb3, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xe2, 0x85, 0x1c, 0x31, 0x52, 0x03, 0x00,
	0x00,
}
