// Code generated by "stringer -type=Code"; DO NOT EDIT.

package codes

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Unknown-0]
	_ = x[OK-1]
	_ = x[Marshal-2]
	_ = x[Unmarshal-3]
	_ = x[TooManyMapLeaves-4]
	_ = x[NoMsgs-5]
	_ = x[NoValidMutations-6]
	_ = x[NilKeyset-7]
	_ = x[NewVerifier-8]
	_ = x[PermissionDenied-9]
	_ = x[PreviousHash-10]
	_ = x[TooLarge-11]
	_ = x[Replay-12]
}

const _Code_name = "UnknownOKMarshalUnmarshalTooManyMapLeavesNoMsgsNoValidMutationsNilKeysetNewVerifierPermissionDeniedPreviousHashTooLargeReplay"

var _Code_index = [...]uint8{0, 7, 9, 16, 25, 41, 47, 63, 72, 83, 99, 111, 119, 125}

func (i Code) String() string {
	if i < 0 || i >= Code(len(_Code_index)-1) {
		return "Code(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Code_name[_Code_index[i]:_Code_index[i+1]]
}
