// Code generated by protoc-gen-go. DO NOT EDIT.
// source: v1/keytransparency_proto/keytransparency.proto

/*
Package keytransparency_proto is a generated protocol buffer package.

Key Transparency Service

The Key Transparency Service API consists of a map of user names to public
keys. Each user name also has a history of public keys that have been
associated with it.

It is generated from these files:
	v1/keytransparency_proto/keytransparency.proto
	v1/keytransparency_proto/admin.proto

It has these top-level messages:
	Committed
	EntryUpdate
	Entry
	MutationProof
	MapperMetadata
	UserProfile
	GetEntryRequest
	GetEntryResponse
	ListEntryHistoryRequest
	ListEntryHistoryResponse
	UpdateEntryRequest
	UpdateEntryResponse
	GetEpochRequest
	Epoch
	Domain
	ListDomainsRequest
	ListDomainsResponse
	GetDomainRequest
	CreateDomainRequest
	DeleteDomainRequest
	UndeleteDomainRequest
*/
package keytransparency_proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"
import keyspb "github.com/google/trillian/crypto/keyspb"
import sigpb "github.com/google/trillian/crypto/sigpb"
import trillian "github.com/google/trillian"
import trillian1 "github.com/google/trillian"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Committed represents the data committed to in a cryptographic commitment.
// commitment = HMAC_SHA512_256(key, data)
type Committed struct {
	// key is the 16 byte random commitment key.
	Key []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// data is the data being committed to.
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *Committed) Reset()                    { *m = Committed{} }
func (m *Committed) String() string            { return proto.CompactTextString(m) }
func (*Committed) ProtoMessage()               {}
func (*Committed) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Committed) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *Committed) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

// EntryUpdate contains the user entry update(s).
type EntryUpdate struct {
	// mutation authorizes the change to entry.
	Mutation *Entry `protobuf:"bytes,2,opt,name=mutation" json:"mutation,omitempty"`
	// commitment contains the data committed to in update.commitment.
	Committed *Committed `protobuf:"bytes,3,opt,name=committed" json:"committed,omitempty"`
}

func (m *EntryUpdate) Reset()                    { *m = EntryUpdate{} }
func (m *EntryUpdate) String() string            { return proto.CompactTextString(m) }
func (*EntryUpdate) ProtoMessage()               {}
func (*EntryUpdate) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *EntryUpdate) GetMutation() *Entry {
	if m != nil {
		return m.Mutation
	}
	return nil
}

func (m *EntryUpdate) GetCommitted() *Committed {
	if m != nil {
		return m.Committed
	}
	return nil
}

// Entry is a signed change to a map entry.
// Entry contains a commitment to profile and a set of authorized update keys.
// Entry is placed in the verifiable map as leaf data.
type Entry struct {
	// index is the location of this leaf in the sparse merkle tree.
	Index []byte `protobuf:"bytes,3,opt,name=index,proto3" json:"index,omitempty"`
	// commitment is a cryptographic commitment to arbitrary data.
	Commitment []byte `protobuf:"bytes,6,opt,name=commitment,proto3" json:"commitment,omitempty"`
	// authorized_keys is the set of keys allowed to sign updates for this entry.
	AuthorizedKeys []*keyspb.PublicKey `protobuf:"bytes,7,rep,name=authorized_keys,json=authorizedKeys" json:"authorized_keys,omitempty"`
	// previous contains the hash of the previous entry that this mutation is
	// modifying creating a hash chain of all mutations. The hash used is
	// CommonJSON in "github.com/benlaurie/objecthash/go/objecthash".
	Previous []byte `protobuf:"bytes,8,opt,name=previous,proto3" json:"previous,omitempty"`
	// signatures on key_value. Must be signed by keys from both previous and
	// current epochs. The first proves ownership of new epoch key, and the
	// second proves that the correct owner is making this change.
	Signatures map[string]*sigpb.DigitallySigned `protobuf:"bytes,2,rep,name=signatures" json:"signatures,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *Entry) Reset()                    { *m = Entry{} }
func (m *Entry) String() string            { return proto.CompactTextString(m) }
func (*Entry) ProtoMessage()               {}
func (*Entry) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Entry) GetIndex() []byte {
	if m != nil {
		return m.Index
	}
	return nil
}

func (m *Entry) GetCommitment() []byte {
	if m != nil {
		return m.Commitment
	}
	return nil
}

func (m *Entry) GetAuthorizedKeys() []*keyspb.PublicKey {
	if m != nil {
		return m.AuthorizedKeys
	}
	return nil
}

func (m *Entry) GetPrevious() []byte {
	if m != nil {
		return m.Previous
	}
	return nil
}

func (m *Entry) GetSignatures() map[string]*sigpb.DigitallySigned {
	if m != nil {
		return m.Signatures
	}
	return nil
}

// MutationProof contains the information necessary to compute the new leaf value.
// It contains a) the old leaf value with it's inclusion proof and b) the mutation.
// The new leaf value is computed via:
//       Mutate(leaf_value, mutation)
type MutationProof struct {
	// mutation contains the information needed to modify the old leaf.
	// The format of a mutation is specific to the particular Mutate function being used.
	Mutation *Entry `protobuf:"bytes,1,opt,name=mutation" json:"mutation,omitempty"`
	// leaf_proof contains the leaf and its inclusion proof for a particular map revision.
	LeafProof *trillian1.MapLeafInclusion `protobuf:"bytes,2,opt,name=leaf_proof,json=leafProof" json:"leaf_proof,omitempty"`
}

func (m *MutationProof) Reset()                    { *m = MutationProof{} }
func (m *MutationProof) String() string            { return proto.CompactTextString(m) }
func (*MutationProof) ProtoMessage()               {}
func (*MutationProof) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *MutationProof) GetMutation() *Entry {
	if m != nil {
		return m.Mutation
	}
	return nil
}

func (m *MutationProof) GetLeafProof() *trillian1.MapLeafInclusion {
	if m != nil {
		return m.LeafProof
	}
	return nil
}

// MapperMetadata tracks the mutations that have been mapped so far. It is
// embedded in the Trillian SignedMapHead.
type MapperMetadata struct {
	HighestFullyCompletedSeq int64 `protobuf:"varint,1,opt,name=highest_fully_completed_seq,json=highestFullyCompletedSeq" json:"highest_fully_completed_seq,omitempty"`
}

func (m *MapperMetadata) Reset()                    { *m = MapperMetadata{} }
func (m *MapperMetadata) String() string            { return proto.CompactTextString(m) }
func (*MapperMetadata) ProtoMessage()               {}
func (*MapperMetadata) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *MapperMetadata) GetHighestFullyCompletedSeq() int64 {
	if m != nil {
		return m.HighestFullyCompletedSeq
	}
	return 0
}

// UserProfile is the data that a client would like to store on the server.
type UserProfile struct {
	// data is the public key data for the user.
	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *UserProfile) Reset()                    { *m = UserProfile{} }
func (m *UserProfile) String() string            { return proto.CompactTextString(m) }
func (*UserProfile) ProtoMessage()               {}
func (*UserProfile) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *UserProfile) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

// GetEntryRequest for a user object.
type GetEntryRequest struct {
	// domain_id identifies the domain in which the user and application live.
	DomainId string `protobuf:"bytes,4,opt,name=domain_id,json=domainId" json:"domain_id,omitempty"`
	// user_id is the user identifier. Most commonly an email address.
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	// app_id is the identifier for the application.
	AppId string `protobuf:"bytes,2,opt,name=app_id,json=appId" json:"app_id,omitempty"`
	// first_tree_size is the tree_size of the currently trusted log root.
	// Omitting this field will omit the log consistency proof from the response.
	FirstTreeSize int64 `protobuf:"varint,3,opt,name=first_tree_size,json=firstTreeSize" json:"first_tree_size,omitempty"`
}

func (m *GetEntryRequest) Reset()                    { *m = GetEntryRequest{} }
func (m *GetEntryRequest) String() string            { return proto.CompactTextString(m) }
func (*GetEntryRequest) ProtoMessage()               {}
func (*GetEntryRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *GetEntryRequest) GetDomainId() string {
	if m != nil {
		return m.DomainId
	}
	return ""
}

func (m *GetEntryRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *GetEntryRequest) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *GetEntryRequest) GetFirstTreeSize() int64 {
	if m != nil {
		return m.FirstTreeSize
	}
	return 0
}

// GetEntryResponse returns a requested user entry.
type GetEntryResponse struct {
	// vrf_proof is the proof for VRF on user_id.
	VrfProof []byte `protobuf:"bytes,1,opt,name=vrf_proof,json=vrfProof,proto3" json:"vrf_proof,omitempty"`
	// committed contains the profile for this account and connects the data
	// in profile to the commitment in leaf_proof.
	Committed *Committed `protobuf:"bytes,2,opt,name=committed" json:"committed,omitempty"`
	// leaf_proof contains an Entry and an inclusion proof in the sparse Merkle
	// Tree.
	LeafProof *trillian1.MapLeafInclusion `protobuf:"bytes,3,opt,name=leaf_proof,json=leafProof" json:"leaf_proof,omitempty"`
	// smr contains the signed map head for the sparse Merkle Tree.
	// smr is also stored in the append only log.
	Smr *trillian.SignedMapRoot `protobuf:"bytes,4,opt,name=smr" json:"smr,omitempty"`
	// log_root is the latest globally consistent log root.
	// TODO: gossip the log root to verify global consistency.
	LogRoot *trillian.SignedLogRoot `protobuf:"bytes,5,opt,name=log_root,json=logRoot" json:"log_root,omitempty"`
	// log_consistency proves that log_root is consistent with previously seen roots.
	LogConsistency [][]byte `protobuf:"bytes,6,rep,name=log_consistency,json=logConsistency,proto3" json:"log_consistency,omitempty"`
	// log_inclusion proves that smr is part of log_root at index=srm.MapRevision.
	LogInclusion [][]byte `protobuf:"bytes,7,rep,name=log_inclusion,json=logInclusion,proto3" json:"log_inclusion,omitempty"`
}

func (m *GetEntryResponse) Reset()                    { *m = GetEntryResponse{} }
func (m *GetEntryResponse) String() string            { return proto.CompactTextString(m) }
func (*GetEntryResponse) ProtoMessage()               {}
func (*GetEntryResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *GetEntryResponse) GetVrfProof() []byte {
	if m != nil {
		return m.VrfProof
	}
	return nil
}

func (m *GetEntryResponse) GetCommitted() *Committed {
	if m != nil {
		return m.Committed
	}
	return nil
}

func (m *GetEntryResponse) GetLeafProof() *trillian1.MapLeafInclusion {
	if m != nil {
		return m.LeafProof
	}
	return nil
}

func (m *GetEntryResponse) GetSmr() *trillian.SignedMapRoot {
	if m != nil {
		return m.Smr
	}
	return nil
}

func (m *GetEntryResponse) GetLogRoot() *trillian.SignedLogRoot {
	if m != nil {
		return m.LogRoot
	}
	return nil
}

func (m *GetEntryResponse) GetLogConsistency() [][]byte {
	if m != nil {
		return m.LogConsistency
	}
	return nil
}

func (m *GetEntryResponse) GetLogInclusion() [][]byte {
	if m != nil {
		return m.LogInclusion
	}
	return nil
}

// ListEntryHistoryRequest gets a list of historical keys for a user.
type ListEntryHistoryRequest struct {
	// domain_id identifies the domain in which the user and application live.
	DomainId string `protobuf:"bytes,6,opt,name=domain_id,json=domainId" json:"domain_id,omitempty"`
	// user_id is the user identifier.
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	// start is the starting epoch.
	Start int64 `protobuf:"varint,2,opt,name=start" json:"start,omitempty"`
	// page_size is the maximum number of entries to return.
	PageSize int32 `protobuf:"varint,3,opt,name=page_size,json=pageSize" json:"page_size,omitempty"`
	// app_id is the identifier for the application.
	AppId string `protobuf:"bytes,4,opt,name=app_id,json=appId" json:"app_id,omitempty"`
	// first_tree_size is the tree_size of the currently trusted log root.
	// Omitting this field will omit the log consistency proof from the response.
	FirstTreeSize int64 `protobuf:"varint,5,opt,name=first_tree_size,json=firstTreeSize" json:"first_tree_size,omitempty"`
}

func (m *ListEntryHistoryRequest) Reset()                    { *m = ListEntryHistoryRequest{} }
func (m *ListEntryHistoryRequest) String() string            { return proto.CompactTextString(m) }
func (*ListEntryHistoryRequest) ProtoMessage()               {}
func (*ListEntryHistoryRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *ListEntryHistoryRequest) GetDomainId() string {
	if m != nil {
		return m.DomainId
	}
	return ""
}

func (m *ListEntryHistoryRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *ListEntryHistoryRequest) GetStart() int64 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *ListEntryHistoryRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *ListEntryHistoryRequest) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *ListEntryHistoryRequest) GetFirstTreeSize() int64 {
	if m != nil {
		return m.FirstTreeSize
	}
	return 0
}

// ListEntryHistoryResponse requests a paginated history of keys for a user.
type ListEntryHistoryResponse struct {
	// values represents the list of keys this user_id has contained over time.
	Values []*GetEntryResponse `protobuf:"bytes,1,rep,name=values" json:"values,omitempty"`
	// next_start is the next page token to query for pagination.
	// next_start is 0 when there are no more results to fetch.
	NextStart int64 `protobuf:"varint,2,opt,name=next_start,json=nextStart" json:"next_start,omitempty"`
}

func (m *ListEntryHistoryResponse) Reset()                    { *m = ListEntryHistoryResponse{} }
func (m *ListEntryHistoryResponse) String() string            { return proto.CompactTextString(m) }
func (*ListEntryHistoryResponse) ProtoMessage()               {}
func (*ListEntryHistoryResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *ListEntryHistoryResponse) GetValues() []*GetEntryResponse {
	if m != nil {
		return m.Values
	}
	return nil
}

func (m *ListEntryHistoryResponse) GetNextStart() int64 {
	if m != nil {
		return m.NextStart
	}
	return 0
}

// UpdateEntryRequest updates a user's profile.
type UpdateEntryRequest struct {
	// domain_id identifies the domain in which the user and application live.
	DomainId string `protobuf:"bytes,5,opt,name=domain_id,json=domainId" json:"domain_id,omitempty"`
	// user_id specifies the id for the user who's profile is being updated.
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	// app_id is the identifier for the application.
	AppId string `protobuf:"bytes,2,opt,name=app_id,json=appId" json:"app_id,omitempty"`
	// first_tree_size is the tree_size of the currently trusted log root.
	// Omitting this field will omit the log consistency proof from the response.
	FirstTreeSize int64 `protobuf:"varint,3,opt,name=first_tree_size,json=firstTreeSize" json:"first_tree_size,omitempty"`
	// entry_update contains the user submitted update.
	EntryUpdate *EntryUpdate `protobuf:"bytes,4,opt,name=entry_update,json=entryUpdate" json:"entry_update,omitempty"`
}

func (m *UpdateEntryRequest) Reset()                    { *m = UpdateEntryRequest{} }
func (m *UpdateEntryRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateEntryRequest) ProtoMessage()               {}
func (*UpdateEntryRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *UpdateEntryRequest) GetDomainId() string {
	if m != nil {
		return m.DomainId
	}
	return ""
}

func (m *UpdateEntryRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *UpdateEntryRequest) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *UpdateEntryRequest) GetFirstTreeSize() int64 {
	if m != nil {
		return m.FirstTreeSize
	}
	return 0
}

func (m *UpdateEntryRequest) GetEntryUpdate() *EntryUpdate {
	if m != nil {
		return m.EntryUpdate
	}
	return nil
}

// UpdateEntryResponse contains a proof once the update has been included in
// the Merkle Tree.
type UpdateEntryResponse struct {
	// proof contains a proof that the update has been included in the tree.
	Proof *GetEntryResponse `protobuf:"bytes,1,opt,name=proof" json:"proof,omitempty"`
}

func (m *UpdateEntryResponse) Reset()                    { *m = UpdateEntryResponse{} }
func (m *UpdateEntryResponse) String() string            { return proto.CompactTextString(m) }
func (*UpdateEntryResponse) ProtoMessage()               {}
func (*UpdateEntryResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *UpdateEntryResponse) GetProof() *GetEntryResponse {
	if m != nil {
		return m.Proof
	}
	return nil
}

// GetEpochRequest identifies a particular epoch.
type GetEpochRequest struct {
	// domain_id is the domain for which epochs are being requested.
	DomainId string `protobuf:"bytes,5,opt,name=domain_id,json=domainId" json:"domain_id,omitempty"`
	// epoch specifies the epoch number in which mutations will be returned.
	Epoch int64 `protobuf:"varint,1,opt,name=epoch" json:"epoch,omitempty"`
	// first_tree_size is the tree_size of the currently trusted log root.
	// Omitting this field will omit the log consistency proof from the response.
	FirstTreeSize int64 `protobuf:"varint,2,opt,name=first_tree_size,json=firstTreeSize" json:"first_tree_size,omitempty"`
}

func (m *GetEpochRequest) Reset()                    { *m = GetEpochRequest{} }
func (m *GetEpochRequest) String() string            { return proto.CompactTextString(m) }
func (*GetEpochRequest) ProtoMessage()               {}
func (*GetEpochRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *GetEpochRequest) GetDomainId() string {
	if m != nil {
		return m.DomainId
	}
	return ""
}

func (m *GetEpochRequest) GetEpoch() int64 {
	if m != nil {
		return m.Epoch
	}
	return 0
}

func (m *GetEpochRequest) GetFirstTreeSize() int64 {
	if m != nil {
		return m.FirstTreeSize
	}
	return 0
}

// Epoch represents a snapshot of the entire key directory and
// a diff of what changed between this revision and the previous revision.
type Epoch struct {
	DomainId string `protobuf:"bytes,1,opt,name=domain_id,json=domainId" json:"domain_id,omitempty"`
	// smr contains the signed map root for the sparse Merkle Tree.
	Smr *trillian.SignedMapRoot `protobuf:"bytes,2,opt,name=smr" json:"smr,omitempty"`
	// log_root is the latest globally consistent log root.
	LogRoot *trillian.SignedLogRoot `protobuf:"bytes,3,opt,name=log_root,json=logRoot" json:"log_root,omitempty"`
	// log_consistency proves that log_root is consistent with previously seen roots.
	LogConsistency [][]byte `protobuf:"bytes,4,rep,name=log_consistency,json=logConsistency,proto3" json:"log_consistency,omitempty"`
	// log_inclusion proves that smr is part of log_root at index=srm.MapRevision.
	LogInclusion [][]byte `protobuf:"bytes,5,rep,name=log_inclusion,json=logInclusion,proto3" json:"log_inclusion,omitempty"`
	// mutation contains mutation information.
	Mutations []*MutationProof `protobuf:"bytes,6,rep,name=mutations" json:"mutations,omitempty"`
	// next_page_token is the next page token to query for pagination.
	// An empty value means there are no more results to fetch.
	// A non-zero value may be used by the client to fetch the next page of
	// results.
	NextPageToken string `protobuf:"bytes,7,opt,name=next_page_token,json=nextPageToken" json:"next_page_token,omitempty"`
}

func (m *Epoch) Reset()                    { *m = Epoch{} }
func (m *Epoch) String() string            { return proto.CompactTextString(m) }
func (*Epoch) ProtoMessage()               {}
func (*Epoch) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *Epoch) GetDomainId() string {
	if m != nil {
		return m.DomainId
	}
	return ""
}

func (m *Epoch) GetSmr() *trillian.SignedMapRoot {
	if m != nil {
		return m.Smr
	}
	return nil
}

func (m *Epoch) GetLogRoot() *trillian.SignedLogRoot {
	if m != nil {
		return m.LogRoot
	}
	return nil
}

func (m *Epoch) GetLogConsistency() [][]byte {
	if m != nil {
		return m.LogConsistency
	}
	return nil
}

func (m *Epoch) GetLogInclusion() [][]byte {
	if m != nil {
		return m.LogInclusion
	}
	return nil
}

func (m *Epoch) GetMutations() []*MutationProof {
	if m != nil {
		return m.Mutations
	}
	return nil
}

func (m *Epoch) GetNextPageToken() string {
	if m != nil {
		return m.NextPageToken
	}
	return ""
}

func init() {
	proto.RegisterType((*Committed)(nil), "google.keytransparency.v1.Committed")
	proto.RegisterType((*EntryUpdate)(nil), "google.keytransparency.v1.EntryUpdate")
	proto.RegisterType((*Entry)(nil), "google.keytransparency.v1.Entry")
	proto.RegisterType((*MutationProof)(nil), "google.keytransparency.v1.MutationProof")
	proto.RegisterType((*MapperMetadata)(nil), "google.keytransparency.v1.MapperMetadata")
	proto.RegisterType((*UserProfile)(nil), "google.keytransparency.v1.UserProfile")
	proto.RegisterType((*GetEntryRequest)(nil), "google.keytransparency.v1.GetEntryRequest")
	proto.RegisterType((*GetEntryResponse)(nil), "google.keytransparency.v1.GetEntryResponse")
	proto.RegisterType((*ListEntryHistoryRequest)(nil), "google.keytransparency.v1.ListEntryHistoryRequest")
	proto.RegisterType((*ListEntryHistoryResponse)(nil), "google.keytransparency.v1.ListEntryHistoryResponse")
	proto.RegisterType((*UpdateEntryRequest)(nil), "google.keytransparency.v1.UpdateEntryRequest")
	proto.RegisterType((*UpdateEntryResponse)(nil), "google.keytransparency.v1.UpdateEntryResponse")
	proto.RegisterType((*GetEpochRequest)(nil), "google.keytransparency.v1.GetEpochRequest")
	proto.RegisterType((*Epoch)(nil), "google.keytransparency.v1.Epoch")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for KeyTransparencyService service

type KeyTransparencyServiceClient interface {
	// GetDomain returns the information needed to verify the specified domain.
	GetDomain(ctx context.Context, in *GetDomainRequest, opts ...grpc.CallOption) (*Domain, error)
	// GetEpoch returns a list of mutations between an epoch and its predecessor.
	//
	// Returns a list of mutations and their inclusion proofs along with the epoch
	// signed map root.
	GetEpoch(ctx context.Context, in *GetEpochRequest, opts ...grpc.CallOption) (*Epoch, error)
	// GetEpochStream streams new epochs as they are created.
	//
	// Returns a list of mutations and their inclusion proofs along with the epoch
	// signed map root.
	GetEpochStream(ctx context.Context, in *GetEpochRequest, opts ...grpc.CallOption) (KeyTransparencyService_GetEpochStreamClient, error)
	// GetEntry returns a user's entry in the Merkle Tree.
	//
	// Entries contain signed commitments to a profile, which is also returned.
	// TODO(gbelvin): Replace with GetUser
	GetEntry(ctx context.Context, in *GetEntryRequest, opts ...grpc.CallOption) (*GetEntryResponse, error)
	// ListEntryHistory returns a list of historic GetEntry values.
	//
	// Clients verify their account history by observing correct values for their
	// account over time.
	ListEntryHistory(ctx context.Context, in *ListEntryHistoryRequest, opts ...grpc.CallOption) (*ListEntryHistoryResponse, error)
	// UpdateEntry updates a user's profile.
	//
	// Returns the current user profile.
	// Clients must retry until this function returns a proof containing the desired value.
	UpdateEntry(ctx context.Context, in *UpdateEntryRequest, opts ...grpc.CallOption) (*UpdateEntryResponse, error)
}

type keyTransparencyServiceClient struct {
	cc *grpc.ClientConn
}

func NewKeyTransparencyServiceClient(cc *grpc.ClientConn) KeyTransparencyServiceClient {
	return &keyTransparencyServiceClient{cc}
}

func (c *keyTransparencyServiceClient) GetDomain(ctx context.Context, in *GetDomainRequest, opts ...grpc.CallOption) (*Domain, error) {
	out := new(Domain)
	err := grpc.Invoke(ctx, "/google.keytransparency.v1.KeyTransparencyService/GetDomain", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyTransparencyServiceClient) GetEpoch(ctx context.Context, in *GetEpochRequest, opts ...grpc.CallOption) (*Epoch, error) {
	out := new(Epoch)
	err := grpc.Invoke(ctx, "/google.keytransparency.v1.KeyTransparencyService/GetEpoch", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyTransparencyServiceClient) GetEpochStream(ctx context.Context, in *GetEpochRequest, opts ...grpc.CallOption) (KeyTransparencyService_GetEpochStreamClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_KeyTransparencyService_serviceDesc.Streams[0], c.cc, "/google.keytransparency.v1.KeyTransparencyService/GetEpochStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &keyTransparencyServiceGetEpochStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type KeyTransparencyService_GetEpochStreamClient interface {
	Recv() (*Epoch, error)
	grpc.ClientStream
}

type keyTransparencyServiceGetEpochStreamClient struct {
	grpc.ClientStream
}

func (x *keyTransparencyServiceGetEpochStreamClient) Recv() (*Epoch, error) {
	m := new(Epoch)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *keyTransparencyServiceClient) GetEntry(ctx context.Context, in *GetEntryRequest, opts ...grpc.CallOption) (*GetEntryResponse, error) {
	out := new(GetEntryResponse)
	err := grpc.Invoke(ctx, "/google.keytransparency.v1.KeyTransparencyService/GetEntry", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyTransparencyServiceClient) ListEntryHistory(ctx context.Context, in *ListEntryHistoryRequest, opts ...grpc.CallOption) (*ListEntryHistoryResponse, error) {
	out := new(ListEntryHistoryResponse)
	err := grpc.Invoke(ctx, "/google.keytransparency.v1.KeyTransparencyService/ListEntryHistory", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyTransparencyServiceClient) UpdateEntry(ctx context.Context, in *UpdateEntryRequest, opts ...grpc.CallOption) (*UpdateEntryResponse, error) {
	out := new(UpdateEntryResponse)
	err := grpc.Invoke(ctx, "/google.keytransparency.v1.KeyTransparencyService/UpdateEntry", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for KeyTransparencyService service

type KeyTransparencyServiceServer interface {
	// GetDomain returns the information needed to verify the specified domain.
	GetDomain(context.Context, *GetDomainRequest) (*Domain, error)
	// GetEpoch returns a list of mutations between an epoch and its predecessor.
	//
	// Returns a list of mutations and their inclusion proofs along with the epoch
	// signed map root.
	GetEpoch(context.Context, *GetEpochRequest) (*Epoch, error)
	// GetEpochStream streams new epochs as they are created.
	//
	// Returns a list of mutations and their inclusion proofs along with the epoch
	// signed map root.
	GetEpochStream(*GetEpochRequest, KeyTransparencyService_GetEpochStreamServer) error
	// GetEntry returns a user's entry in the Merkle Tree.
	//
	// Entries contain signed commitments to a profile, which is also returned.
	// TODO(gbelvin): Replace with GetUser
	GetEntry(context.Context, *GetEntryRequest) (*GetEntryResponse, error)
	// ListEntryHistory returns a list of historic GetEntry values.
	//
	// Clients verify their account history by observing correct values for their
	// account over time.
	ListEntryHistory(context.Context, *ListEntryHistoryRequest) (*ListEntryHistoryResponse, error)
	// UpdateEntry updates a user's profile.
	//
	// Returns the current user profile.
	// Clients must retry until this function returns a proof containing the desired value.
	UpdateEntry(context.Context, *UpdateEntryRequest) (*UpdateEntryResponse, error)
}

func RegisterKeyTransparencyServiceServer(s *grpc.Server, srv KeyTransparencyServiceServer) {
	s.RegisterService(&_KeyTransparencyService_serviceDesc, srv)
}

func _KeyTransparencyService_GetDomain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDomainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyTransparencyServiceServer).GetDomain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/google.keytransparency.v1.KeyTransparencyService/GetDomain",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyTransparencyServiceServer).GetDomain(ctx, req.(*GetDomainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyTransparencyService_GetEpoch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEpochRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyTransparencyServiceServer).GetEpoch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/google.keytransparency.v1.KeyTransparencyService/GetEpoch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyTransparencyServiceServer).GetEpoch(ctx, req.(*GetEpochRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyTransparencyService_GetEpochStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetEpochRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(KeyTransparencyServiceServer).GetEpochStream(m, &keyTransparencyServiceGetEpochStreamServer{stream})
}

type KeyTransparencyService_GetEpochStreamServer interface {
	Send(*Epoch) error
	grpc.ServerStream
}

type keyTransparencyServiceGetEpochStreamServer struct {
	grpc.ServerStream
}

func (x *keyTransparencyServiceGetEpochStreamServer) Send(m *Epoch) error {
	return x.ServerStream.SendMsg(m)
}

func _KeyTransparencyService_GetEntry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEntryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyTransparencyServiceServer).GetEntry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/google.keytransparency.v1.KeyTransparencyService/GetEntry",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyTransparencyServiceServer).GetEntry(ctx, req.(*GetEntryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyTransparencyService_ListEntryHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListEntryHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyTransparencyServiceServer).ListEntryHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/google.keytransparency.v1.KeyTransparencyService/ListEntryHistory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyTransparencyServiceServer).ListEntryHistory(ctx, req.(*ListEntryHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyTransparencyService_UpdateEntry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateEntryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyTransparencyServiceServer).UpdateEntry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/google.keytransparency.v1.KeyTransparencyService/UpdateEntry",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyTransparencyServiceServer).UpdateEntry(ctx, req.(*UpdateEntryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _KeyTransparencyService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "google.keytransparency.v1.KeyTransparencyService",
	HandlerType: (*KeyTransparencyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDomain",
			Handler:    _KeyTransparencyService_GetDomain_Handler,
		},
		{
			MethodName: "GetEpoch",
			Handler:    _KeyTransparencyService_GetEpoch_Handler,
		},
		{
			MethodName: "GetEntry",
			Handler:    _KeyTransparencyService_GetEntry_Handler,
		},
		{
			MethodName: "ListEntryHistory",
			Handler:    _KeyTransparencyService_ListEntryHistory_Handler,
		},
		{
			MethodName: "UpdateEntry",
			Handler:    _KeyTransparencyService_UpdateEntry_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetEpochStream",
			Handler:       _KeyTransparencyService_GetEpochStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "v1/keytransparency_proto/keytransparency.proto",
}

func init() { proto.RegisterFile("v1/keytransparency_proto/keytransparency.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1244 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x57, 0xdd, 0x6e, 0x1b, 0x45,
	0x14, 0xd6, 0xda, 0xb1, 0x63, 0x1f, 0xe7, 0xa7, 0x0c, 0xa5, 0xd9, 0xba, 0xfc, 0xa4, 0x4b, 0x69,
	0x43, 0xa1, 0xde, 0xc6, 0x15, 0x02, 0x22, 0x2a, 0x44, 0xd3, 0xb4, 0x44, 0x69, 0x44, 0xb4, 0x69,
	0x25, 0xc4, 0xcd, 0x6a, 0xe2, 0x1d, 0x6f, 0x46, 0x5d, 0xef, 0x6c, 0x67, 0xc6, 0x56, 0xdd, 0x10,
	0x2e, 0xb8, 0x40, 0xbd, 0xeb, 0x05, 0x6f, 0xc0, 0x5b, 0x70, 0x83, 0x54, 0x5e, 0x01, 0x6e, 0x10,
	0xb7, 0x3c, 0x08, 0x9a, 0x1f, 0xff, 0xc4, 0x89, 0x9d, 0x38, 0x42, 0xdc, 0x78, 0x77, 0xce, 0x9c,
	0x33, 0xf3, 0xcd, 0x77, 0xbe, 0x73, 0xc6, 0x0b, 0xb5, 0xce, 0xaa, 0xff, 0x94, 0x74, 0x25, 0xc7,
	0xa9, 0xc8, 0x30, 0x27, 0x69, 0xa3, 0x1b, 0x66, 0x9c, 0x49, 0x36, 0x6a, 0xad, 0x69, 0x2b, 0xba,
	0x1c, 0x33, 0x16, 0x27, 0xa4, 0x36, 0x3a, 0xdb, 0x59, 0xad, 0xbe, 0x6d, 0xa6, 0x7c, 0x9c, 0x51,
	0x1f, 0xa7, 0x29, 0x93, 0x58, 0x52, 0x96, 0x0a, 0x13, 0x58, 0xad, 0x36, 0x78, 0x37, 0x33, 0xcb,
	0x8a, 0x6c, 0xcf, 0x3e, 0xec, 0x9c, 0x6b, 0xe7, 0x04, 0x8d, 0xb3, 0x3d, 0xf3, 0x6b, 0x67, 0x16,
	0x24, 0xa7, 0x49, 0x42, 0x71, 0x6a, 0xc7, 0x97, 0x7a, 0xe3, 0xb0, 0x85, 0xb3, 0x10, 0x67, 0xd4,
	0xda, 0xaf, 0x8d, 0x3d, 0x06, 0x8e, 0x5a, 0xd4, 0x46, 0x7b, 0xab, 0x50, 0x5e, 0x67, 0xad, 0x16,
	0x95, 0x92, 0x44, 0xe8, 0x02, 0xe4, 0x9f, 0x92, 0xae, 0xeb, 0x2c, 0x3b, 0x2b, 0x73, 0x81, 0x7a,
	0x45, 0x08, 0x66, 0x22, 0x2c, 0xb1, 0x9b, 0xd3, 0x26, 0xfd, 0xee, 0xbd, 0x72, 0xa0, 0xb2, 0x91,
	0x4a, 0xde, 0x7d, 0x92, 0x45, 0x58, 0x12, 0xf4, 0x05, 0x94, 0x5a, 0x6d, 0x73, 0x32, 0xed, 0x57,
	0xa9, 0x2f, 0xd7, 0xc6, 0x52, 0x52, 0xd3, 0x91, 0x41, 0x3f, 0x02, 0xdd, 0x83, 0x72, 0xa3, 0x07,
	0xc0, 0xcd, 0xeb, 0xf0, 0x6b, 0x13, 0xc2, 0xfb, 0x60, 0x83, 0x41, 0x98, 0xf7, 0x5b, 0x0e, 0x0a,
	0x7a, 0x5d, 0x74, 0x11, 0x0a, 0x34, 0x8d, 0xc8, 0x73, 0xbd, 0xd2, 0x5c, 0x60, 0x06, 0xe8, 0x5d,
	0x00, 0xe3, 0xdc, 0x22, 0xa9, 0x74, 0x8b, 0x7a, 0x6a, 0xc8, 0x82, 0xd6, 0x60, 0x11, 0xb7, 0xe5,
	0x3e, 0xe3, 0xf4, 0x05, 0x89, 0x42, 0x95, 0x07, 0x77, 0x76, 0x39, 0xbf, 0x52, 0xa9, 0xbf, 0x51,
	0xb3, 0x49, 0xd9, 0x69, 0xef, 0x25, 0xb4, 0xb1, 0x45, 0xba, 0xc1, 0xc2, 0xc0, 0x73, 0x8b, 0x74,
	0x05, 0xaa, 0x42, 0x29, 0xe3, 0xa4, 0x43, 0x59, 0x5b, 0xb8, 0x25, 0xbd, 0x72, 0x7f, 0x8c, 0x76,
	0x00, 0x04, 0x8d, 0x53, 0x2c, 0xdb, 0x9c, 0x08, 0x37, 0xa7, 0x97, 0xbc, 0x7d, 0x1a, 0x37, 0xb5,
	0xdd, 0x7e, 0x88, 0xe1, 0x6a, 0x68, 0x8d, 0xea, 0x13, 0x58, 0x1c, 0x99, 0x1e, 0x4e, 0x5a, 0xd9,
	0x24, 0xed, 0x63, 0x28, 0x74, 0x70, 0xd2, 0x26, 0x36, 0x1b, 0x97, 0x6a, 0x46, 0x3e, 0xf7, 0x69,
	0x4c, 0x25, 0x4e, 0x92, 0xae, 0x5a, 0x81, 0x44, 0x81, 0x71, 0x5a, 0xcb, 0x7d, 0xe6, 0x78, 0x2f,
	0x1d, 0x98, 0xdf, 0xb6, 0x19, 0xd9, 0xe1, 0x8c, 0x35, 0x8f, 0x24, 0xd5, 0x99, 0x3a, 0xa9, 0x9f,
	0x03, 0x24, 0x04, 0x37, 0x95, 0xde, 0x58, 0xd3, 0xc2, 0xa8, 0xd6, 0xfa, 0xc2, 0xdd, 0xc6, 0xd9,
	0x23, 0x82, 0x9b, 0x9b, 0x69, 0x23, 0x69, 0x0b, 0xca, 0xd2, 0xa0, 0xac, 0xbc, 0xf5, 0xc6, 0xde,
	0x37, 0xb0, 0xb0, 0x8d, 0xb3, 0x8c, 0xf0, 0x6d, 0x22, 0xb1, 0xd2, 0x1b, 0xba, 0x0b, 0x57, 0xf6,
	0x69, 0xbc, 0x4f, 0x84, 0x0c, 0x9b, 0xed, 0x24, 0xe9, 0x86, 0x0d, 0xd6, 0xca, 0x12, 0x22, 0x49,
	0x14, 0x0a, 0xf2, 0x4c, 0xa3, 0xcb, 0x07, 0xae, 0x75, 0x79, 0xa0, 0x3c, 0xd6, 0x7b, 0x0e, 0xbb,
	0xe4, 0x99, 0x77, 0x15, 0x2a, 0x4f, 0x04, 0xe1, 0x3b, 0x9c, 0x35, 0x69, 0x42, 0xfa, 0x8a, 0x76,
	0x86, 0x14, 0xfd, 0x93, 0x03, 0x8b, 0x0f, 0x89, 0x34, 0xa7, 0x20, 0xcf, 0xda, 0x44, 0x48, 0x74,
	0x05, 0xca, 0x11, 0x6b, 0x61, 0x9a, 0x86, 0x34, 0x72, 0x67, 0x34, 0xb9, 0x25, 0x63, 0xd8, 0x8c,
	0xd0, 0x12, 0xcc, 0xb6, 0x05, 0xe1, 0x6a, 0xca, 0xf0, 0x5e, 0x54, 0xc3, 0xcd, 0x08, 0xbd, 0x05,
	0x45, 0x9c, 0x65, 0xca, 0x9e, 0xd3, 0xf6, 0x02, 0xce, 0xb2, 0xcd, 0x08, 0x5d, 0x87, 0xc5, 0x26,
	0xe5, 0x42, 0x86, 0x92, 0x13, 0x12, 0x0a, 0xfa, 0x82, 0x68, 0x81, 0xe6, 0x83, 0x79, 0x6d, 0x7e,
	0xcc, 0x09, 0xd9, 0xa5, 0x2f, 0x88, 0xf7, 0x77, 0x0e, 0x2e, 0x0c, 0x80, 0x88, 0x8c, 0xa5, 0x82,
	0x28, 0x24, 0x1d, 0xde, 0xe3, 0xd2, 0xc0, 0x2e, 0x75, 0xb8, 0xa1, 0xeb, 0x68, 0xf9, 0xe4, 0xce,
	0x55, 0x3e, 0x23, 0xd9, 0xca, 0x4f, 0x91, 0x2d, 0xf4, 0x21, 0xe4, 0x45, 0x8b, 0x6b, 0x7e, 0x2a,
	0xf5, 0xa5, 0x41, 0x8c, 0x91, 0xd8, 0x36, 0xce, 0x02, 0xc6, 0x64, 0xa0, 0x7c, 0x50, 0x1d, 0x4a,
	0x09, 0x8b, 0x43, 0xce, 0x98, 0x74, 0x0b, 0x27, 0xfb, 0x3f, 0x62, 0xb1, 0xf6, 0x9f, 0x4d, 0xcc,
	0x0b, 0xba, 0x01, 0x8b, 0x2a, 0xa6, 0xc1, 0x52, 0x41, 0x85, 0x54, 0x87, 0x70, 0x8b, 0xcb, 0xf9,
	0x95, 0xb9, 0x60, 0x21, 0x61, 0xf1, 0xfa, 0xc0, 0x8a, 0xde, 0x87, 0x79, 0xe5, 0x48, 0x7b, 0x18,
	0x75, 0xfd, 0xce, 0x05, 0x73, 0x09, 0x8b, 0xfb, 0xb8, 0xbd, 0xd7, 0x0e, 0x2c, 0x3d, 0xa2, 0xc2,
	0xd0, 0xfb, 0x35, 0x15, 0x92, 0x8d, 0x49, 0x77, 0xf1, 0xac, 0xe9, 0xbe, 0x08, 0x05, 0x21, 0x31,
	0x97, 0x9a, 0xf9, 0x7c, 0x60, 0x06, 0x6a, 0xad, 0x0c, 0xc7, 0x43, 0x79, 0x2e, 0x04, 0x25, 0x65,
	0x50, 0x29, 0x1e, 0x52, 0xc8, 0xcc, 0x29, 0x0a, 0x29, 0x9c, 0xa4, 0x90, 0x1f, 0xc0, 0x3d, 0x7e,
	0x04, 0x2b, 0x94, 0x75, 0x28, 0xea, 0x92, 0x16, 0xae, 0xa3, 0x5b, 0xcd, 0x47, 0x13, 0x84, 0x30,
	0xaa, 0xb2, 0xc0, 0x86, 0xa2, 0x77, 0x00, 0x52, 0xf2, 0x5c, 0x86, 0xc3, 0xe7, 0x2a, 0x2b, 0xcb,
	0xae, 0x32, 0x78, 0x7f, 0x3a, 0x80, 0x4c, 0xdf, 0x1f, 0x5f, 0x2d, 0x85, 0xff, 0xa7, 0x5a, 0xd0,
	0x26, 0xcc, 0x11, 0x05, 0x22, 0x6c, 0x6b, 0x40, 0x56, 0x85, 0xd7, 0x4f, 0xeb, 0x53, 0x06, 0x7e,
	0x50, 0x21, 0x83, 0x81, 0xf7, 0x2d, 0xbc, 0x79, 0xe4, 0x54, 0x96, 0xd1, 0xaf, 0xa0, 0x30, 0x28,
	0xbb, 0x29, 0x09, 0x35, 0x91, 0x5e, 0x62, 0x5a, 0x4b, 0xc6, 0x1a, 0xfb, 0x67, 0x22, 0xeb, 0x22,
	0x14, 0x88, 0x72, 0xb6, 0x7d, 0xcd, 0x0c, 0x4e, 0xa2, 0x24, 0x77, 0x92, 0x3c, 0x5e, 0xab, 0x9b,
	0x50, 0x47, 0x1c, 0xd9, 0xc4, 0x19, 0xd9, 0xc4, 0x96, 0x6d, 0x6e, 0xca, 0xb2, 0xcd, 0x9f, 0xbf,
	0x6c, 0x67, 0xce, 0x56, 0xb6, 0x85, 0xe3, 0x65, 0x8b, 0x1e, 0x40, 0xb9, 0x77, 0xb1, 0x08, 0x5d,
	0xfe, 0x95, 0xfa, 0xca, 0x84, 0x44, 0x1c, 0xb9, 0xc7, 0x82, 0x41, 0xa8, 0xe2, 0x50, 0x2b, 0x5b,
	0xd7, 0xa6, 0x64, 0x4f, 0x89, 0xea, 0x12, 0x8a, 0x97, 0x79, 0x65, 0xde, 0xc1, 0x31, 0x79, 0xac,
	0x8c, 0xf5, 0xbf, 0x66, 0xe1, 0xd2, 0x16, 0xe9, 0x3e, 0x1e, 0x5a, 0x77, 0x97, 0xf0, 0x0e, 0x6d,
	0x10, 0xf4, 0x3d, 0x94, 0x1f, 0x12, 0x79, 0x5f, 0xd3, 0x88, 0x4e, 0x51, 0x83, 0xf1, 0xb2, 0x39,
	0xaf, 0x5e, 0x9d, 0xe0, 0x6c, 0x3c, 0xbd, 0xf7, 0x7e, 0xfc, 0xe3, 0x9f, 0x9f, 0x73, 0x97, 0xd1,
	0x92, 0xdf, 0x59, 0xf5, 0x4d, 0xaa, 0x84, 0x7f, 0xd0, 0x4f, 0xe2, 0x21, 0x7a, 0xe9, 0x40, 0xa9,
	0xa7, 0x25, 0x74, 0xf3, 0x14, 0x2d, 0x0e, 0x09, 0xae, 0x3a, 0xf1, 0xea, 0x56, 0x8e, 0x5e, 0x4d,
	0xef, 0xbd, 0x82, 0xae, 0x8f, 0xd9, 0xdb, 0xd7, 0x32, 0x14, 0xfe, 0x81, 0x7e, 0x1e, 0xa2, 0x57,
	0x0e, 0x2c, 0xf4, 0x76, 0xd9, 0x95, 0x9c, 0xe0, 0xd6, 0x7f, 0x0c, 0xe8, 0x96, 0x06, 0x74, 0x03,
	0x7d, 0x30, 0x19, 0xd0, 0x9a, 0xd0, 0x9b, 0xdf, 0x76, 0xd0, 0x2f, 0x96, 0x1c, 0xfd, 0x9f, 0xe8,
	0xe6, 0x99, 0x0a, 0xd5, 0x60, 0x99, 0xa6, 0xa8, 0xbd, 0xbb, 0x1a, 0xd6, 0xa7, 0xe8, 0x93, 0x71,
	0xb0, 0x70, 0x96, 0x09, 0xff, 0xc0, 0x74, 0xb5, 0x43, 0x5f, 0xf5, 0x39, 0xe1, 0x1f, 0xd8, 0xee,
	0x77, 0x88, 0x7e, 0x77, 0xe0, 0xc2, 0x68, 0xfb, 0x46, 0xf5, 0x09, 0x00, 0xc6, 0x5c, 0x57, 0xd5,
	0x3b, 0x53, 0xc5, 0x58, 0xf0, 0x1b, 0x1a, 0xfc, 0x97, 0xe8, 0xee, 0xb9, 0xc0, 0xfb, 0xfb, 0x16,
	0xef, 0xaf, 0x0e, 0x54, 0x86, 0x9a, 0x25, 0xba, 0x35, 0x01, 0xcb, 0xf1, 0xab, 0xa2, 0x5a, 0x3b,
	0xab, 0xbb, 0x45, 0xbd, 0xa5, 0x51, 0x6f, 0x54, 0xcf, 0x47, 0xf9, 0xda, 0x91, 0x2b, 0xe2, 0xde,
	0xc6, 0x77, 0xeb, 0x31, 0x95, 0xfb, 0xed, 0xbd, 0x5a, 0x83, 0xb5, 0x7c, 0xfb, 0x75, 0x36, 0x02,
	0xc4, 0x6f, 0x30, 0x6e, 0x3e, 0xd9, 0xc6, 0x7d, 0x41, 0xed, 0x15, 0xf5, 0xe3, 0xce, 0xbf, 0x01,
	0x00, 0x00, 0xff, 0xff, 0xf2, 0x25, 0xd7, 0xe8, 0x2b, 0x0e, 0x00, 0x00,
}
