// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/keytransparency_v1_proto/keytransparency_v1_admin_proto.proto

package keytransparency_v1_proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import trillian "github.com/google/trillian"
import keyspb "github.com/google/trillian/crypto/keyspb"
import google_protobuf1 "github.com/golang/protobuf/ptypes/duration"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// BatchUpdateEntriesRequest will update the accounts of the given user_ids to be set to
// user data if those accounts have key_id in their set of authorized_keys.
type BatchUpdateEntriesRequest struct {
	// users is a map from user_ids to user data.
	Users map[string]*UserProfile `protobuf:"bytes,1,rep,name=users" json:"users,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// app_id is the application to make this change for.
	AppId string `protobuf:"bytes,2,opt,name=app_id,json=appId" json:"app_id,omitempty"`
	// auth_pub_key_id is the id of the authorized_public key to use when updating accounts.
	// This must be a key that this server has the private key for.
	AuthPubKeyId string `protobuf:"bytes,3,opt,name=auth_pub_key_id,json=authPubKeyId" json:"auth_pub_key_id,omitempty"`
}

func (m *BatchUpdateEntriesRequest) Reset()                    { *m = BatchUpdateEntriesRequest{} }
func (m *BatchUpdateEntriesRequest) String() string            { return proto.CompactTextString(m) }
func (*BatchUpdateEntriesRequest) ProtoMessage()               {}
func (*BatchUpdateEntriesRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *BatchUpdateEntriesRequest) GetUsers() map[string]*UserProfile {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *BatchUpdateEntriesRequest) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *BatchUpdateEntriesRequest) GetAuthPubKeyId() string {
	if m != nil {
		return m.AuthPubKeyId
	}
	return ""
}

// BatchUpdateEntriesResponse returns a list of users for which the set operation
// was unsuccessful.
type BatchUpdateEntriesResponse struct {
	// errors is a map from user_ids to errors, if there was an error for that user.
	Errors map[string]string `protobuf:"bytes,1,rep,name=errors" json:"errors,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *BatchUpdateEntriesResponse) Reset()                    { *m = BatchUpdateEntriesResponse{} }
func (m *BatchUpdateEntriesResponse) String() string            { return proto.CompactTextString(m) }
func (*BatchUpdateEntriesResponse) ProtoMessage()               {}
func (*BatchUpdateEntriesResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *BatchUpdateEntriesResponse) GetErrors() map[string]string {
	if m != nil {
		return m.Errors
	}
	return nil
}

// Domain contains information on a single domain
type Domain struct {
	// DomainId can be any URL safe string.
	DomainId string `protobuf:"bytes,1,opt,name=domain_id,json=domainId" json:"domain_id,omitempty"`
	// Log contains the Log-Tree's info.
	Log *trillian.Tree `protobuf:"bytes,2,opt,name=log" json:"log,omitempty"`
	// Map contains the Map-Tree's info.
	Map *trillian.Tree `protobuf:"bytes,3,opt,name=map" json:"map,omitempty"`
	// Vrf contains the VRF public key.
	Vrf *keyspb.PublicKey `protobuf:"bytes,4,opt,name=vrf" json:"vrf,omitempty"`
	// min_interval is the minimum time between epochs.
	MinInterval *google_protobuf1.Duration `protobuf:"bytes,5,opt,name=min_interval,json=minInterval" json:"min_interval,omitempty"`
	// max_interval is the maximum time between epochs.
	MaxInterval *google_protobuf1.Duration `protobuf:"bytes,6,opt,name=max_interval,json=maxInterval" json:"max_interval,omitempty"`
	// Deleted indicates whether the domain has been marked as deleted.
	// By its presence in a response, this domain has not been garbage collected.
	Deleted bool `protobuf:"varint,7,opt,name=deleted" json:"deleted,omitempty"`
}

func (m *Domain) Reset()                    { *m = Domain{} }
func (m *Domain) String() string            { return proto.CompactTextString(m) }
func (*Domain) ProtoMessage()               {}
func (*Domain) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *Domain) GetDomainId() string {
	if m != nil {
		return m.DomainId
	}
	return ""
}

func (m *Domain) GetLog() *trillian.Tree {
	if m != nil {
		return m.Log
	}
	return nil
}

func (m *Domain) GetMap() *trillian.Tree {
	if m != nil {
		return m.Map
	}
	return nil
}

func (m *Domain) GetVrf() *keyspb.PublicKey {
	if m != nil {
		return m.Vrf
	}
	return nil
}

func (m *Domain) GetMinInterval() *google_protobuf1.Duration {
	if m != nil {
		return m.MinInterval
	}
	return nil
}

func (m *Domain) GetMaxInterval() *google_protobuf1.Duration {
	if m != nil {
		return m.MaxInterval
	}
	return nil
}

func (m *Domain) GetDeleted() bool {
	if m != nil {
		return m.Deleted
	}
	return false
}

// ListDomains request.
// No pagination options are provided.
type ListDomainsRequest struct {
	// showDeleted requests domains that have been marked for deletion
	// but have not been garbage collected.
	ShowDeleted bool `protobuf:"varint,1,opt,name=show_deleted,json=showDeleted" json:"show_deleted,omitempty"`
}

func (m *ListDomainsRequest) Reset()                    { *m = ListDomainsRequest{} }
func (m *ListDomainsRequest) String() string            { return proto.CompactTextString(m) }
func (*ListDomainsRequest) ProtoMessage()               {}
func (*ListDomainsRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *ListDomainsRequest) GetShowDeleted() bool {
	if m != nil {
		return m.ShowDeleted
	}
	return false
}

// ListDomains response contains domains.
type ListDomainsResponse struct {
	Domains []*Domain `protobuf:"bytes,1,rep,name=domains" json:"domains,omitempty"`
}

func (m *ListDomainsResponse) Reset()                    { *m = ListDomainsResponse{} }
func (m *ListDomainsResponse) String() string            { return proto.CompactTextString(m) }
func (*ListDomainsResponse) ProtoMessage()               {}
func (*ListDomainsResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

func (m *ListDomainsResponse) GetDomains() []*Domain {
	if m != nil {
		return m.Domains
	}
	return nil
}

// GetDomainRequest specifies the domain to retrieve information for.
type GetDomainRequest struct {
	DomainId string `protobuf:"bytes,1,opt,name=domain_id,json=domainId" json:"domain_id,omitempty"`
	// showDeleted requests domains that have been marked for deletion
	// but have not been garbage collected.
	ShowDeleted bool `protobuf:"varint,2,opt,name=show_deleted,json=showDeleted" json:"show_deleted,omitempty"`
}

func (m *GetDomainRequest) Reset()                    { *m = GetDomainRequest{} }
func (m *GetDomainRequest) String() string            { return proto.CompactTextString(m) }
func (*GetDomainRequest) ProtoMessage()               {}
func (*GetDomainRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{5} }

func (m *GetDomainRequest) GetDomainId() string {
	if m != nil {
		return m.DomainId
	}
	return ""
}

func (m *GetDomainRequest) GetShowDeleted() bool {
	if m != nil {
		return m.ShowDeleted
	}
	return false
}

// GetDomainResponse contains the configuration info for one domain.
type GetDomainResponse struct {
	Domain *Domain `protobuf:"bytes,1,opt,name=domain" json:"domain,omitempty"`
}

func (m *GetDomainResponse) Reset()                    { *m = GetDomainResponse{} }
func (m *GetDomainResponse) String() string            { return proto.CompactTextString(m) }
func (*GetDomainResponse) ProtoMessage()               {}
func (*GetDomainResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{6} }

func (m *GetDomainResponse) GetDomain() *Domain {
	if m != nil {
		return m.Domain
	}
	return nil
}

// CreateDomainRequest creates a new domain
type CreateDomainRequest struct {
	DomainId    string                     `protobuf:"bytes,1,opt,name=domain_id,json=domainId" json:"domain_id,omitempty"`
	MinInterval *google_protobuf1.Duration `protobuf:"bytes,2,opt,name=min_interval,json=minInterval" json:"min_interval,omitempty"`
	MaxInterval *google_protobuf1.Duration `protobuf:"bytes,3,opt,name=max_interval,json=maxInterval" json:"max_interval,omitempty"`
}

func (m *CreateDomainRequest) Reset()                    { *m = CreateDomainRequest{} }
func (m *CreateDomainRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateDomainRequest) ProtoMessage()               {}
func (*CreateDomainRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{7} }

func (m *CreateDomainRequest) GetDomainId() string {
	if m != nil {
		return m.DomainId
	}
	return ""
}

func (m *CreateDomainRequest) GetMinInterval() *google_protobuf1.Duration {
	if m != nil {
		return m.MinInterval
	}
	return nil
}

func (m *CreateDomainRequest) GetMaxInterval() *google_protobuf1.Duration {
	if m != nil {
		return m.MaxInterval
	}
	return nil
}

// CreateDomainResponse contains the configuration info for the new domain.
type CreateDomainResponse struct {
	Domain *Domain `protobuf:"bytes,1,opt,name=domain" json:"domain,omitempty"`
}

func (m *CreateDomainResponse) Reset()                    { *m = CreateDomainResponse{} }
func (m *CreateDomainResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateDomainResponse) ProtoMessage()               {}
func (*CreateDomainResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{8} }

func (m *CreateDomainResponse) GetDomain() *Domain {
	if m != nil {
		return m.Domain
	}
	return nil
}

// DeleteDomainRequest deletes a domain
type DeleteDomainRequest struct {
	DomainId string `protobuf:"bytes,1,opt,name=domain_id,json=domainId" json:"domain_id,omitempty"`
}

func (m *DeleteDomainRequest) Reset()                    { *m = DeleteDomainRequest{} }
func (m *DeleteDomainRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteDomainRequest) ProtoMessage()               {}
func (*DeleteDomainRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{9} }

func (m *DeleteDomainRequest) GetDomainId() string {
	if m != nil {
		return m.DomainId
	}
	return ""
}

// UndeleteDomainRequest deletes a domain
type UndeleteDomainRequest struct {
	DomainId string `protobuf:"bytes,1,opt,name=domain_id,json=domainId" json:"domain_id,omitempty"`
}

func (m *UndeleteDomainRequest) Reset()                    { *m = UndeleteDomainRequest{} }
func (m *UndeleteDomainRequest) String() string            { return proto.CompactTextString(m) }
func (*UndeleteDomainRequest) ProtoMessage()               {}
func (*UndeleteDomainRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{10} }

func (m *UndeleteDomainRequest) GetDomainId() string {
	if m != nil {
		return m.DomainId
	}
	return ""
}

func init() {
	proto.RegisterType((*BatchUpdateEntriesRequest)(nil), "keytransparency.v1.proto.BatchUpdateEntriesRequest")
	proto.RegisterType((*BatchUpdateEntriesResponse)(nil), "keytransparency.v1.proto.BatchUpdateEntriesResponse")
	proto.RegisterType((*Domain)(nil), "keytransparency.v1.proto.Domain")
	proto.RegisterType((*ListDomainsRequest)(nil), "keytransparency.v1.proto.ListDomainsRequest")
	proto.RegisterType((*ListDomainsResponse)(nil), "keytransparency.v1.proto.ListDomainsResponse")
	proto.RegisterType((*GetDomainRequest)(nil), "keytransparency.v1.proto.GetDomainRequest")
	proto.RegisterType((*GetDomainResponse)(nil), "keytransparency.v1.proto.GetDomainResponse")
	proto.RegisterType((*CreateDomainRequest)(nil), "keytransparency.v1.proto.CreateDomainRequest")
	proto.RegisterType((*CreateDomainResponse)(nil), "keytransparency.v1.proto.CreateDomainResponse")
	proto.RegisterType((*DeleteDomainRequest)(nil), "keytransparency.v1.proto.DeleteDomainRequest")
	proto.RegisterType((*UndeleteDomainRequest)(nil), "keytransparency.v1.proto.UndeleteDomainRequest")
}

func init() {
	proto.RegisterFile("proto/keytransparency_v1_proto/keytransparency_v1_admin_proto.proto", fileDescriptor1)
}

var fileDescriptor1 = []byte{
	// 635 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0x5d, 0x4f, 0xdb, 0x30,
	0x14, 0x55, 0xda, 0xb5, 0xc0, 0x2d, 0x62, 0x10, 0x40, 0x0a, 0x9d, 0x34, 0x75, 0x99, 0x90, 0x78,
	0x4a, 0x05, 0x9b, 0x34, 0xc6, 0x3e, 0x34, 0xf1, 0x21, 0x54, 0xb1, 0x49, 0x5d, 0x04, 0xd2, 0xb4,
	0x97, 0xc8, 0x69, 0x2e, 0xad, 0x45, 0x1a, 0x7b, 0x8e, 0xd3, 0x91, 0x7f, 0xb1, 0x1f, 0xb1, 0xe7,
	0x49, 0xfb, 0x87, 0x53, 0x6c, 0xb7, 0x94, 0x8e, 0x6c, 0x54, 0xbc, 0x34, 0xf1, 0xbd, 0xf7, 0x9c,
	0x1e, 0x1f, 0x9f, 0x18, 0x8e, 0xb8, 0x60, 0x92, 0xb5, 0xaf, 0x30, 0x97, 0x82, 0x24, 0x29, 0x27,
	0x02, 0x93, 0x5e, 0x1e, 0x8c, 0x76, 0x83, 0xd2, 0x06, 0x89, 0x86, 0x34, 0xd1, 0x6d, 0x4f, 0xfd,
	0xda, 0xce, 0xcc, 0x94, 0x37, 0xda, 0xd5, 0x9d, 0xe6, 0x8a, 0x14, 0x34, 0x8e, 0x29, 0x49, 0xcc,
	0xba, 0xd9, 0x13, 0x39, 0xd7, 0xb4, 0x29, 0x0f, 0xcd, 0xc3, 0xf4, 0xde, 0xcd, 0x2f, 0x65, 0x4a,
	0x44, 0xf3, 0x69, 0x9f, 0xb1, 0x7e, 0x8c, 0x6d, 0xb5, 0x0a, 0xb3, 0xcb, 0x76, 0x94, 0x09, 0x22,
	0x29, 0x33, 0x7f, 0xed, 0xfe, 0xa8, 0xc0, 0xd6, 0x21, 0x91, 0xbd, 0xc1, 0x05, 0x8f, 0x88, 0xc4,
	0x93, 0x44, 0x0a, 0x8a, 0xa9, 0x8f, 0xdf, 0x32, 0x4c, 0xa5, 0x7d, 0x0e, 0xb5, 0x2c, 0x45, 0x91,
	0x3a, 0x56, 0xab, 0xba, 0xd3, 0xd8, 0x7b, 0xef, 0x95, 0x6d, 0xc9, 0x2b, 0xe5, 0xf0, 0x2e, 0x0a,
	0x82, 0xa2, 0x96, 0xfb, 0x9a, 0xcc, 0xde, 0x84, 0x3a, 0xe1, 0x3c, 0xa0, 0x91, 0x53, 0x69, 0x59,
	0x3b, 0x4b, 0x7e, 0x8d, 0x70, 0xde, 0x89, 0xec, 0x6d, 0x78, 0x4c, 0x32, 0x39, 0x08, 0x78, 0x16,
	0x06, 0x57, 0x98, 0x17, 0xfd, 0xaa, 0xea, 0x2f, 0x17, 0xe5, 0x6e, 0x16, 0x9e, 0x61, 0xde, 0x89,
	0x9a, 0x01, 0xc0, 0x0d, 0xa5, 0xbd, 0x0a, 0xd5, 0x2b, 0xcc, 0x1d, 0x4b, 0x0d, 0x16, 0xaf, 0xf6,
	0x1b, 0xa8, 0x8d, 0x48, 0x9c, 0xa1, 0x22, 0x6f, 0xec, 0x6d, 0x97, 0x6b, 0x2e, 0x68, 0xba, 0x82,
	0x5d, 0xd2, 0x18, 0x7d, 0x8d, 0x39, 0xa8, 0xec, 0x5b, 0xee, 0x6f, 0x0b, 0x9a, 0x77, 0x6d, 0x27,
	0xe5, 0x2c, 0x49, 0xd1, 0xfe, 0x02, 0x75, 0x14, 0x82, 0x4d, 0x4c, 0xf9, 0x30, 0x9f, 0x29, 0x9a,
	0xc5, 0x3b, 0x51, 0x14, 0xda, 0x16, 0xc3, 0xd7, 0x7c, 0x0d, 0x8d, 0xa9, 0xf2, 0x1d, 0x5b, 0xdb,
	0x98, 0xde, 0xda, 0xd2, 0xb4, 0xe6, 0x9f, 0x15, 0xa8, 0x1f, 0xb3, 0x21, 0xa1, 0x89, 0xfd, 0x04,
	0x96, 0x22, 0xf5, 0x56, 0x18, 0xa8, 0xc1, 0x8b, 0xba, 0xd0, 0x89, 0xec, 0x16, 0x54, 0x63, 0xd6,
	0x37, 0xd6, 0xac, 0x78, 0x93, 0x1c, 0x9e, 0x0b, 0x44, 0xbf, 0x68, 0x15, 0x13, 0x43, 0xc2, 0x95,
	0xf3, 0x77, 0x4c, 0x0c, 0x09, 0xb7, 0x9f, 0x43, 0x75, 0x24, 0x2e, 0x9d, 0x47, 0x6a, 0x62, 0xcd,
	0x33, 0x69, 0xed, 0x66, 0x61, 0x4c, 0x7b, 0x67, 0x98, 0xfb, 0x45, 0xd7, 0x7e, 0x0b, 0xcb, 0xc5,
	0xf7, 0x40, 0x13, 0x89, 0x62, 0x44, 0x62, 0xa7, 0xa6, 0xa6, 0xb7, 0x3c, 0x1d, 0x47, 0x6f, 0x1c,
	0x47, 0xef, 0xd8, 0xc4, 0xd1, 0x6f, 0x0c, 0x69, 0xd2, 0x31, 0xd3, 0x0a, 0x4d, 0xae, 0x6f, 0xd0,
	0xf5, 0xff, 0xa3, 0xc9, 0xf5, 0x04, 0xed, 0xc0, 0x42, 0x84, 0x31, 0x4a, 0x8c, 0x9c, 0x85, 0x96,
	0xb5, 0xb3, 0xe8, 0x8f, 0x97, 0xee, 0x2b, 0xb0, 0x3f, 0xd2, 0x54, 0x6a, 0xa7, 0x26, 0x29, 0x7f,
	0x06, 0xcb, 0xe9, 0x80, 0x7d, 0x0f, 0xc6, 0x20, 0x4b, 0x81, 0x1a, 0x45, 0xed, 0xd8, 0x00, 0x3f,
	0xc3, 0xfa, 0x2d, 0xa0, 0xc9, 0xc2, 0x01, 0x2c, 0x68, 0x6b, 0xc7, 0x61, 0x68, 0x95, 0x87, 0x41,
	0x63, 0xfd, 0x31, 0xc0, 0xf5, 0x61, 0xf5, 0x14, 0x0d, 0xe3, 0x58, 0xc9, 0x3f, 0xcf, 0x6e, 0x56,
	0x66, 0xe5, 0x6f, 0x99, 0x9f, 0x60, 0x6d, 0x8a, 0xd3, 0x88, 0xdc, 0x87, 0xba, 0xe6, 0x50, 0x8c,
	0xf7, 0xd1, 0x68, 0xe6, 0xdd, 0x5f, 0x16, 0xac, 0x1f, 0x09, 0x24, 0x12, 0xe7, 0x90, 0x39, 0x7b,
	0xf2, 0x95, 0x07, 0x9d, 0x7c, 0x75, 0x9e, 0x93, 0x77, 0xbb, 0xb0, 0x71, 0x5b, 0xef, 0x83, 0x2d,
	0xd8, 0x83, 0x75, 0x6d, 0xee, 0xfd, 0x1d, 0x70, 0x5f, 0xc2, 0xe6, 0x45, 0x12, 0xcd, 0x89, 0x3a,
	0x3c, 0xfd, 0x7a, 0xd2, 0xa7, 0x72, 0x90, 0x85, 0x5e, 0x8f, 0x0d, 0xdb, 0xe6, 0xda, 0x9e, 0x91,
	0xd9, 0xee, 0x31, 0x61, 0xee, 0xf2, 0xd2, 0x8b, 0x3f, 0xac, 0xab, 0xc7, 0x8b, 0x3f, 0x01, 0x00,
	0x00, 0xff, 0xff, 0x9f, 0x14, 0x3c, 0xe0, 0xc5, 0x06, 0x00, 0x00,
}
